package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.PrtbcTipopers;
import pe.gob.sunafil.gestionpersonal.persistence.model.PrtbcTipopersExample;

public interface PrtbcTipopersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int countByExample(PrtbcTipopersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int deleteByExample(PrtbcTipopersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int deleteByPrimaryKey(String vCodtipo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insert(PrtbcTipopers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insertSelective(PrtbcTipopers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    List<PrtbcTipopers> selectByExample(PrtbcTipopersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    PrtbcTipopers selectByPrimaryKey(String vCodtipo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") PrtbcTipopers record, @Param("example") PrtbcTipopersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExample(@Param("record") PrtbcTipopers record, @Param("example") PrtbcTipopersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByPrimaryKeySelective(PrtbcTipopers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.PRTBC_TIPOPERS
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByPrimaryKey(PrtbcTipopers record);
}