package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhtbdPerxentfinanciera;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhtbdPerxentfinancieraExample;

public interface RhtbdPerxentfinancieraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int countByExample(RhtbdPerxentfinancieraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int deleteByExample(RhtbdPerxentfinancieraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int deleteByPrimaryKey(BigDecimal nCorperentfin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insert(RhtbdPerxentfinanciera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insertSelective(RhtbdPerxentfinanciera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    List<RhtbdPerxentfinanciera> selectByExample(RhtbdPerxentfinancieraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    RhtbdPerxentfinanciera selectByPrimaryKey(BigDecimal nCorperentfin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") RhtbdPerxentfinanciera record, @Param("example") RhtbdPerxentfinancieraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExample(@Param("record") RhtbdPerxentfinanciera record, @Param("example") RhtbdPerxentfinancieraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByPrimaryKeySelective(RhtbdPerxentfinanciera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERXENTFINANCIERA
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByPrimaryKey(RhtbdPerxentfinanciera record);
}