package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.SitbDistrito;
import pe.gob.sunafil.gestionpersonal.persistence.model.SitbDistritoExample;
import pe.gob.sunafil.gestionpersonal.persistence.model.SitbDistritoKey;

public interface SitbDistritoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int countByExample(SitbDistritoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int deleteByExample(SitbDistritoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int deleteByPrimaryKey(SitbDistritoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insert(SitbDistrito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insertSelective(SitbDistrito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    List<SitbDistrito> selectByExample(SitbDistritoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    SitbDistrito selectByPrimaryKey(SitbDistritoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") SitbDistrito record, @Param("example") SitbDistritoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExample(@Param("record") SitbDistrito record, @Param("example") SitbDistritoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByPrimaryKeySelective(SitbDistrito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_DISTRITO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByPrimaryKey(SitbDistrito record);
}