package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstProfesion;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstProfesionExample;

public interface VstProfesionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_PROFESION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int countByExample(VstProfesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_PROFESION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int deleteByExample(VstProfesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_PROFESION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insert(VstProfesion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_PROFESION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insertSelective(VstProfesion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_PROFESION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    List<VstProfesion> selectByExample(VstProfesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_PROFESION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") VstProfesion record, @Param("example") VstProfesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_PROFESION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExample(@Param("record") VstProfesion record, @Param("example") VstProfesionExample example);
}