package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstResolucion;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstResolucionExample;

public interface VstResolucionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_RESOLUCION
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    int countByExample(VstResolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_RESOLUCION
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    int deleteByExample(VstResolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_RESOLUCION
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    int insert(VstResolucion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_RESOLUCION
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    int insertSelective(VstResolucion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_RESOLUCION
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    List<VstResolucion> selectByExample(VstResolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_RESOLUCION
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    int updateByExampleSelective(@Param("record") VstResolucion record, @Param("example") VstResolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_RESOLUCION
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    int updateByExample(@Param("record") VstResolucion record, @Param("example") VstResolucionExample example);
}