package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstTurnopersonalrrhh;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstTurnopersonalrrhhExample;

public interface VstTurnopersonalrrhhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_TURNOPERSONALRRHH
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int countByExample(VstTurnopersonalrrhhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_TURNOPERSONALRRHH
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int deleteByExample(VstTurnopersonalrrhhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_TURNOPERSONALRRHH
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insert(VstTurnopersonalrrhh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_TURNOPERSONALRRHH
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int insertSelective(VstTurnopersonalrrhh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_TURNOPERSONALRRHH
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    List<VstTurnopersonalrrhh> selectByExample(VstTurnopersonalrrhhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_TURNOPERSONALRRHH
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") VstTurnopersonalrrhh record, @Param("example") VstTurnopersonalrrhhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_TURNOPERSONALRRHH
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    int updateByExample(@Param("record") VstTurnopersonalrrhh record, @Param("example") VstTurnopersonalrrhhExample example);
}