package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhtbcSindicato;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhtbcSindicatoExample;

public interface RhtbcSindicatoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int countByExample(RhtbcSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int deleteByExample(RhtbcSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int deleteByPrimaryKey(BigDecimal nCodsindic);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int insert(RhtbcSindicato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int insertSelective(RhtbcSindicato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    List<RhtbcSindicato> selectByExample(RhtbcSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    RhtbcSindicato selectByPrimaryKey(BigDecimal nCodsindic);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int updateByExampleSelective(@Param("record") RhtbcSindicato record, @Param("example") RhtbcSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int updateByExample(@Param("record") RhtbcSindicato record, @Param("example") RhtbcSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int updateByPrimaryKeySelective(RhtbcSindicato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_SINDICATO
     *
     * @mbggenerated Thu Mar 16 10:52:59 COT 2017
     */
    int updateByPrimaryKey(RhtbcSindicato record);
}