package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhtbcEstpermiso;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhtbcEstpermisoExample;

public interface RhtbcEstpermisoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int countByExample(RhtbcEstpermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int deleteByExample(RhtbcEstpermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int deleteByPrimaryKey(BigDecimal nCodestper);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int insert(RhtbcEstpermiso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int insertSelective(RhtbcEstpermiso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    List<RhtbcEstpermiso> selectByExample(RhtbcEstpermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    RhtbcEstpermiso selectByPrimaryKey(BigDecimal nCodestper);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int updateByExampleSelective(@Param("record") RhtbcEstpermiso record, @Param("example") RhtbcEstpermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int updateByExample(@Param("record") RhtbcEstpermiso record, @Param("example") RhtbcEstpermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int updateByPrimaryKeySelective(RhtbcEstpermiso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ESTPERMISO
     *
     * @mbggenerated Thu Mar 02 12:30:53 COT 2017
     */
    int updateByPrimaryKey(RhtbcEstpermiso record);
}