package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.SitbTdocide;
import pe.gob.sunafil.gestionpersonal.persistence.model.SitbTdocideExample;

public interface SitbTdocideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int countByExample(SitbTdocideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int deleteByExample(SitbTdocideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int insert(SitbTdocide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int insertSelective(SitbTdocide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    List<SitbTdocide> selectByExample(SitbTdocideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    SitbTdocide selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int updateByExampleSelective(@Param("record") SitbTdocide record, @Param("example") SitbTdocideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int updateByExample(@Param("record") SitbTdocide record, @Param("example") SitbTdocideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int updateByPrimaryKeySelective(SitbTdocide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TDOCIDE
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int updateByPrimaryKey(SitbTdocide record);
}