package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstRegpensionario;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstRegpensionarioExample;

public interface VstRegpensionarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_REGPENSIONARIO
     *
     * @mbggenerated Thu Mar 16 17:22:50 COT 2017
     */
    int countByExample(VstRegpensionarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_REGPENSIONARIO
     *
     * @mbggenerated Thu Mar 16 17:22:50 COT 2017
     */
    int deleteByExample(VstRegpensionarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_REGPENSIONARIO
     *
     * @mbggenerated Thu Mar 16 17:22:50 COT 2017
     */
    int insert(VstRegpensionario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_REGPENSIONARIO
     *
     * @mbggenerated Thu Mar 16 17:22:50 COT 2017
     */
    int insertSelective(VstRegpensionario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_REGPENSIONARIO
     *
     * @mbggenerated Thu Mar 16 17:22:50 COT 2017
     */
    List<VstRegpensionario> selectByExample(VstRegpensionarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_REGPENSIONARIO
     *
     * @mbggenerated Thu Mar 16 17:22:50 COT 2017
     */
    int updateByExampleSelective(@Param("record") VstRegpensionario record, @Param("example") VstRegpensionarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_REGPENSIONARIO
     *
     * @mbggenerated Thu Mar 16 17:22:50 COT 2017
     */
    int updateByExample(@Param("record") VstRegpensionario record, @Param("example") VstRegpensionarioExample example);
}