package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstSindicato;
import pe.gob.sunafil.gestionpersonal.persistence.model.VstSindicatoExample;

public interface VstSindicatoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_SINDICATO
     *
     * @mbggenerated Wed Mar 29 09:06:58 COT 2017
     */
    int countByExample(VstSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_SINDICATO
     *
     * @mbggenerated Wed Mar 29 09:06:58 COT 2017
     */
    int deleteByExample(VstSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_SINDICATO
     *
     * @mbggenerated Wed Mar 29 09:06:58 COT 2017
     */
    int insert(VstSindicato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_SINDICATO
     *
     * @mbggenerated Wed Mar 29 09:06:58 COT 2017
     */
    int insertSelective(VstSindicato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_SINDICATO
     *
     * @mbggenerated Wed Mar 29 09:06:58 COT 2017
     */
    List<VstSindicato> selectByExample(VstSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_SINDICATO
     *
     * @mbggenerated Wed Mar 29 09:06:58 COT 2017
     */
    int updateByExampleSelective(@Param("record") VstSindicato record, @Param("example") VstSindicatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.VST_SINDICATO
     *
     * @mbggenerated Wed Mar 29 09:06:58 COT 2017
     */
    int updateByExample(@Param("record") VstSindicato record, @Param("example") VstSindicatoExample example);
}