package pe.gob.sunafil.gestionpersonal.persistence.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RhtbdPerdireccionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public RhtbdPerdireccionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andNCorperdirIsNull() {
            addCriterion("N_CORPERDIR is null");
            return (Criteria) this;
        }

        public Criteria andNCorperdirIsNotNull() {
            addCriterion("N_CORPERDIR is not null");
            return (Criteria) this;
        }

        public Criteria andNCorperdirEqualTo(BigDecimal value) {
            addCriterion("N_CORPERDIR =", value, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirNotEqualTo(BigDecimal value) {
            addCriterion("N_CORPERDIR <>", value, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirGreaterThan(BigDecimal value) {
            addCriterion("N_CORPERDIR >", value, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORPERDIR >=", value, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirLessThan(BigDecimal value) {
            addCriterion("N_CORPERDIR <", value, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORPERDIR <=", value, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirIn(List<BigDecimal> values) {
            addCriterion("N_CORPERDIR in", values, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirNotIn(List<BigDecimal> values) {
            addCriterion("N_CORPERDIR not in", values, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORPERDIR between", value1, value2, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andNCorperdirNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORPERDIR not between", value1, value2, "nCorperdir");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalIsNull() {
            addCriterion("V_CODPERSONAL is null");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalIsNotNull() {
            addCriterion("V_CODPERSONAL is not null");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalEqualTo(String value) {
            addCriterion("V_CODPERSONAL =", value, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalNotEqualTo(String value) {
            addCriterion("V_CODPERSONAL <>", value, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalGreaterThan(String value) {
            addCriterion("V_CODPERSONAL >", value, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODPERSONAL >=", value, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalLessThan(String value) {
            addCriterion("V_CODPERSONAL <", value, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalLessThanOrEqualTo(String value) {
            addCriterion("V_CODPERSONAL <=", value, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalLike(String value) {
            addCriterion("V_CODPERSONAL like", value, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalNotLike(String value) {
            addCriterion("V_CODPERSONAL not like", value, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalIn(List<String> values) {
            addCriterion("V_CODPERSONAL in", values, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalNotIn(List<String> values) {
            addCriterion("V_CODPERSONAL not in", values, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalBetween(String value1, String value2) {
            addCriterion("V_CODPERSONAL between", value1, value2, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCodpersonalNotBetween(String value1, String value2) {
            addCriterion("V_CODPERSONAL not between", value1, value2, "vCodpersonal");
            return (Criteria) this;
        }

        public Criteria andVCoddepIsNull() {
            addCriterion("V_CODDEP is null");
            return (Criteria) this;
        }

        public Criteria andVCoddepIsNotNull() {
            addCriterion("V_CODDEP is not null");
            return (Criteria) this;
        }

        public Criteria andVCoddepEqualTo(String value) {
            addCriterion("V_CODDEP =", value, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepNotEqualTo(String value) {
            addCriterion("V_CODDEP <>", value, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepGreaterThan(String value) {
            addCriterion("V_CODDEP >", value, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODDEP >=", value, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepLessThan(String value) {
            addCriterion("V_CODDEP <", value, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepLessThanOrEqualTo(String value) {
            addCriterion("V_CODDEP <=", value, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepLike(String value) {
            addCriterion("V_CODDEP like", value, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepNotLike(String value) {
            addCriterion("V_CODDEP not like", value, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepIn(List<String> values) {
            addCriterion("V_CODDEP in", values, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepNotIn(List<String> values) {
            addCriterion("V_CODDEP not in", values, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepBetween(String value1, String value2) {
            addCriterion("V_CODDEP between", value1, value2, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCoddepNotBetween(String value1, String value2) {
            addCriterion("V_CODDEP not between", value1, value2, "vCoddep");
            return (Criteria) this;
        }

        public Criteria andVCodproIsNull() {
            addCriterion("V_CODPRO is null");
            return (Criteria) this;
        }

        public Criteria andVCodproIsNotNull() {
            addCriterion("V_CODPRO is not null");
            return (Criteria) this;
        }

        public Criteria andVCodproEqualTo(String value) {
            addCriterion("V_CODPRO =", value, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproNotEqualTo(String value) {
            addCriterion("V_CODPRO <>", value, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproGreaterThan(String value) {
            addCriterion("V_CODPRO >", value, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODPRO >=", value, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproLessThan(String value) {
            addCriterion("V_CODPRO <", value, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproLessThanOrEqualTo(String value) {
            addCriterion("V_CODPRO <=", value, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproLike(String value) {
            addCriterion("V_CODPRO like", value, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproNotLike(String value) {
            addCriterion("V_CODPRO not like", value, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproIn(List<String> values) {
            addCriterion("V_CODPRO in", values, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproNotIn(List<String> values) {
            addCriterion("V_CODPRO not in", values, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproBetween(String value1, String value2) {
            addCriterion("V_CODPRO between", value1, value2, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCodproNotBetween(String value1, String value2) {
            addCriterion("V_CODPRO not between", value1, value2, "vCodpro");
            return (Criteria) this;
        }

        public Criteria andVCoddisIsNull() {
            addCriterion("V_CODDIS is null");
            return (Criteria) this;
        }

        public Criteria andVCoddisIsNotNull() {
            addCriterion("V_CODDIS is not null");
            return (Criteria) this;
        }

        public Criteria andVCoddisEqualTo(String value) {
            addCriterion("V_CODDIS =", value, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisNotEqualTo(String value) {
            addCriterion("V_CODDIS <>", value, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisGreaterThan(String value) {
            addCriterion("V_CODDIS >", value, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODDIS >=", value, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisLessThan(String value) {
            addCriterion("V_CODDIS <", value, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisLessThanOrEqualTo(String value) {
            addCriterion("V_CODDIS <=", value, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisLike(String value) {
            addCriterion("V_CODDIS like", value, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisNotLike(String value) {
            addCriterion("V_CODDIS not like", value, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisIn(List<String> values) {
            addCriterion("V_CODDIS in", values, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisNotIn(List<String> values) {
            addCriterion("V_CODDIS not in", values, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisBetween(String value1, String value2) {
            addCriterion("V_CODDIS between", value1, value2, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCoddisNotBetween(String value1, String value2) {
            addCriterion("V_CODDIS not between", value1, value2, "vCoddis");
            return (Criteria) this;
        }

        public Criteria andVCodzonIsNull() {
            addCriterion("V_CODZON is null");
            return (Criteria) this;
        }

        public Criteria andVCodzonIsNotNull() {
            addCriterion("V_CODZON is not null");
            return (Criteria) this;
        }

        public Criteria andVCodzonEqualTo(String value) {
            addCriterion("V_CODZON =", value, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonNotEqualTo(String value) {
            addCriterion("V_CODZON <>", value, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonGreaterThan(String value) {
            addCriterion("V_CODZON >", value, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODZON >=", value, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonLessThan(String value) {
            addCriterion("V_CODZON <", value, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonLessThanOrEqualTo(String value) {
            addCriterion("V_CODZON <=", value, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonLike(String value) {
            addCriterion("V_CODZON like", value, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonNotLike(String value) {
            addCriterion("V_CODZON not like", value, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonIn(List<String> values) {
            addCriterion("V_CODZON in", values, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonNotIn(List<String> values) {
            addCriterion("V_CODZON not in", values, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonBetween(String value1, String value2) {
            addCriterion("V_CODZON between", value1, value2, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVCodzonNotBetween(String value1, String value2) {
            addCriterion("V_CODZON not between", value1, value2, "vCodzon");
            return (Criteria) this;
        }

        public Criteria andVDeszonaIsNull() {
            addCriterion("V_DESZONA is null");
            return (Criteria) this;
        }

        public Criteria andVDeszonaIsNotNull() {
            addCriterion("V_DESZONA is not null");
            return (Criteria) this;
        }

        public Criteria andVDeszonaEqualTo(String value) {
            addCriterion("V_DESZONA =", value, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaNotEqualTo(String value) {
            addCriterion("V_DESZONA <>", value, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaGreaterThan(String value) {
            addCriterion("V_DESZONA >", value, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaGreaterThanOrEqualTo(String value) {
            addCriterion("V_DESZONA >=", value, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaLessThan(String value) {
            addCriterion("V_DESZONA <", value, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaLessThanOrEqualTo(String value) {
            addCriterion("V_DESZONA <=", value, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaLike(String value) {
            addCriterion("V_DESZONA like", value, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaNotLike(String value) {
            addCriterion("V_DESZONA not like", value, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaIn(List<String> values) {
            addCriterion("V_DESZONA in", values, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaNotIn(List<String> values) {
            addCriterion("V_DESZONA not in", values, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaBetween(String value1, String value2) {
            addCriterion("V_DESZONA between", value1, value2, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVDeszonaNotBetween(String value1, String value2) {
            addCriterion("V_DESZONA not between", value1, value2, "vDeszona");
            return (Criteria) this;
        }

        public Criteria andVCodtviaIsNull() {
            addCriterion("V_CODTVIA is null");
            return (Criteria) this;
        }

        public Criteria andVCodtviaIsNotNull() {
            addCriterion("V_CODTVIA is not null");
            return (Criteria) this;
        }

        public Criteria andVCodtviaEqualTo(String value) {
            addCriterion("V_CODTVIA =", value, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaNotEqualTo(String value) {
            addCriterion("V_CODTVIA <>", value, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaGreaterThan(String value) {
            addCriterion("V_CODTVIA >", value, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODTVIA >=", value, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaLessThan(String value) {
            addCriterion("V_CODTVIA <", value, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaLessThanOrEqualTo(String value) {
            addCriterion("V_CODTVIA <=", value, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaLike(String value) {
            addCriterion("V_CODTVIA like", value, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaNotLike(String value) {
            addCriterion("V_CODTVIA not like", value, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaIn(List<String> values) {
            addCriterion("V_CODTVIA in", values, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaNotIn(List<String> values) {
            addCriterion("V_CODTVIA not in", values, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaBetween(String value1, String value2) {
            addCriterion("V_CODTVIA between", value1, value2, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVCodtviaNotBetween(String value1, String value2) {
            addCriterion("V_CODTVIA not between", value1, value2, "vCodtvia");
            return (Criteria) this;
        }

        public Criteria andVDireccionIsNull() {
            addCriterion("V_DIRECCION is null");
            return (Criteria) this;
        }

        public Criteria andVDireccionIsNotNull() {
            addCriterion("V_DIRECCION is not null");
            return (Criteria) this;
        }

        public Criteria andVDireccionEqualTo(String value) {
            addCriterion("V_DIRECCION =", value, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionNotEqualTo(String value) {
            addCriterion("V_DIRECCION <>", value, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionGreaterThan(String value) {
            addCriterion("V_DIRECCION >", value, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionGreaterThanOrEqualTo(String value) {
            addCriterion("V_DIRECCION >=", value, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionLessThan(String value) {
            addCriterion("V_DIRECCION <", value, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionLessThanOrEqualTo(String value) {
            addCriterion("V_DIRECCION <=", value, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionLike(String value) {
            addCriterion("V_DIRECCION like", value, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionNotLike(String value) {
            addCriterion("V_DIRECCION not like", value, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionIn(List<String> values) {
            addCriterion("V_DIRECCION in", values, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionNotIn(List<String> values) {
            addCriterion("V_DIRECCION not in", values, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionBetween(String value1, String value2) {
            addCriterion("V_DIRECCION between", value1, value2, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVDireccionNotBetween(String value1, String value2) {
            addCriterion("V_DIRECCION not between", value1, value2, "vDireccion");
            return (Criteria) this;
        }

        public Criteria andVCodusuregIsNull() {
            addCriterion("V_CODUSUREG is null");
            return (Criteria) this;
        }

        public Criteria andVCodusuregIsNotNull() {
            addCriterion("V_CODUSUREG is not null");
            return (Criteria) this;
        }

        public Criteria andVCodusuregEqualTo(String value) {
            addCriterion("V_CODUSUREG =", value, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregNotEqualTo(String value) {
            addCriterion("V_CODUSUREG <>", value, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregGreaterThan(String value) {
            addCriterion("V_CODUSUREG >", value, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODUSUREG >=", value, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregLessThan(String value) {
            addCriterion("V_CODUSUREG <", value, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregLessThanOrEqualTo(String value) {
            addCriterion("V_CODUSUREG <=", value, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregLike(String value) {
            addCriterion("V_CODUSUREG like", value, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregNotLike(String value) {
            addCriterion("V_CODUSUREG not like", value, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregIn(List<String> values) {
            addCriterion("V_CODUSUREG in", values, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregNotIn(List<String> values) {
            addCriterion("V_CODUSUREG not in", values, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregBetween(String value1, String value2) {
            addCriterion("V_CODUSUREG between", value1, value2, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andVCodusuregNotBetween(String value1, String value2) {
            addCriterion("V_CODUSUREG not between", value1, value2, "vCodusureg");
            return (Criteria) this;
        }

        public Criteria andDFecregIsNull() {
            addCriterion("D_FECREG is null");
            return (Criteria) this;
        }

        public Criteria andDFecregIsNotNull() {
            addCriterion("D_FECREG is not null");
            return (Criteria) this;
        }

        public Criteria andDFecregEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG =", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG <>", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECREG >", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG >=", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregLessThan(Date value) {
            addCriterionForJDBCDate("D_FECREG <", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG <=", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECREG in", values, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECREG not in", values, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECREG between", value1, value2, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECREG not between", value1, value2, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andVHostregIsNull() {
            addCriterion("V_HOSTREG is null");
            return (Criteria) this;
        }

        public Criteria andVHostregIsNotNull() {
            addCriterion("V_HOSTREG is not null");
            return (Criteria) this;
        }

        public Criteria andVHostregEqualTo(String value) {
            addCriterion("V_HOSTREG =", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotEqualTo(String value) {
            addCriterion("V_HOSTREG <>", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregGreaterThan(String value) {
            addCriterion("V_HOSTREG >", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregGreaterThanOrEqualTo(String value) {
            addCriterion("V_HOSTREG >=", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLessThan(String value) {
            addCriterion("V_HOSTREG <", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLessThanOrEqualTo(String value) {
            addCriterion("V_HOSTREG <=", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLike(String value) {
            addCriterion("V_HOSTREG like", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotLike(String value) {
            addCriterion("V_HOSTREG not like", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregIn(List<String> values) {
            addCriterion("V_HOSTREG in", values, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotIn(List<String> values) {
            addCriterion("V_HOSTREG not in", values, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregBetween(String value1, String value2) {
            addCriterion("V_HOSTREG between", value1, value2, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotBetween(String value1, String value2) {
            addCriterion("V_HOSTREG not between", value1, value2, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVCodusumodIsNull() {
            addCriterion("V_CODUSUMOD is null");
            return (Criteria) this;
        }

        public Criteria andVCodusumodIsNotNull() {
            addCriterion("V_CODUSUMOD is not null");
            return (Criteria) this;
        }

        public Criteria andVCodusumodEqualTo(String value) {
            addCriterion("V_CODUSUMOD =", value, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodNotEqualTo(String value) {
            addCriterion("V_CODUSUMOD <>", value, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodGreaterThan(String value) {
            addCriterion("V_CODUSUMOD >", value, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODUSUMOD >=", value, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodLessThan(String value) {
            addCriterion("V_CODUSUMOD <", value, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodLessThanOrEqualTo(String value) {
            addCriterion("V_CODUSUMOD <=", value, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodLike(String value) {
            addCriterion("V_CODUSUMOD like", value, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodNotLike(String value) {
            addCriterion("V_CODUSUMOD not like", value, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodIn(List<String> values) {
            addCriterion("V_CODUSUMOD in", values, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodNotIn(List<String> values) {
            addCriterion("V_CODUSUMOD not in", values, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodBetween(String value1, String value2) {
            addCriterion("V_CODUSUMOD between", value1, value2, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andVCodusumodNotBetween(String value1, String value2) {
            addCriterion("V_CODUSUMOD not between", value1, value2, "vCodusumod");
            return (Criteria) this;
        }

        public Criteria andDFecmodIsNull() {
            addCriterion("D_FECMOD is null");
            return (Criteria) this;
        }

        public Criteria andDFecmodIsNotNull() {
            addCriterion("D_FECMOD is not null");
            return (Criteria) this;
        }

        public Criteria andDFecmodEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECMOD =", value, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECMOD <>", value, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECMOD >", value, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECMOD >=", value, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodLessThan(Date value) {
            addCriterionForJDBCDate("D_FECMOD <", value, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECMOD <=", value, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECMOD in", values, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECMOD not in", values, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECMOD between", value1, value2, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andDFecmodNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECMOD not between", value1, value2, "dFecmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodIsNull() {
            addCriterion("V_HOSTMOD is null");
            return (Criteria) this;
        }

        public Criteria andVHostmodIsNotNull() {
            addCriterion("V_HOSTMOD is not null");
            return (Criteria) this;
        }

        public Criteria andVHostmodEqualTo(String value) {
            addCriterion("V_HOSTMOD =", value, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodNotEqualTo(String value) {
            addCriterion("V_HOSTMOD <>", value, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodGreaterThan(String value) {
            addCriterion("V_HOSTMOD >", value, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodGreaterThanOrEqualTo(String value) {
            addCriterion("V_HOSTMOD >=", value, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodLessThan(String value) {
            addCriterion("V_HOSTMOD <", value, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodLessThanOrEqualTo(String value) {
            addCriterion("V_HOSTMOD <=", value, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodLike(String value) {
            addCriterion("V_HOSTMOD like", value, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodNotLike(String value) {
            addCriterion("V_HOSTMOD not like", value, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodIn(List<String> values) {
            addCriterion("V_HOSTMOD in", values, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodNotIn(List<String> values) {
            addCriterion("V_HOSTMOD not in", values, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodBetween(String value1, String value2) {
            addCriterion("V_HOSTMOD between", value1, value2, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVHostmodNotBetween(String value1, String value2) {
            addCriterion("V_HOSTMOD not between", value1, value2, "vHostmod");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultIsNull() {
            addCriterion("V_FLGDIRULT is null");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultIsNotNull() {
            addCriterion("V_FLGDIRULT is not null");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultEqualTo(String value) {
            addCriterion("V_FLGDIRULT =", value, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultNotEqualTo(String value) {
            addCriterion("V_FLGDIRULT <>", value, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultGreaterThan(String value) {
            addCriterion("V_FLGDIRULT >", value, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultGreaterThanOrEqualTo(String value) {
            addCriterion("V_FLGDIRULT >=", value, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultLessThan(String value) {
            addCriterion("V_FLGDIRULT <", value, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultLessThanOrEqualTo(String value) {
            addCriterion("V_FLGDIRULT <=", value, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultLike(String value) {
            addCriterion("V_FLGDIRULT like", value, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultNotLike(String value) {
            addCriterion("V_FLGDIRULT not like", value, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultIn(List<String> values) {
            addCriterion("V_FLGDIRULT in", values, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultNotIn(List<String> values) {
            addCriterion("V_FLGDIRULT not in", values, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultBetween(String value1, String value2) {
            addCriterion("V_FLGDIRULT between", value1, value2, "vFlgdirult");
            return (Criteria) this;
        }

        public Criteria andVFlgdirultNotBetween(String value1, String value2) {
            addCriterion("V_FLGDIRULT not between", value1, value2, "vFlgdirult");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 30 08:50:03 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHTBD_PERDIRECCION
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}