package pe.gob.sunafil.gestionpersonal.persistence.model;

import java.math.BigDecimal;

public class SitbSeguro {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_SEGURO.N_CODSEGURO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    private BigDecimal nCodseguro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_SEGURO.V_DESSEGURO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    private String vDesseguro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_SEGURO.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    private String vFlgact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_SEGURO.N_CORTIPSEG
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    private BigDecimal nCortipseg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_SEGURO.N_CODSEGURO
     *
     * @return the value of SIMINTRA1.SITB_SEGURO.N_CODSEGURO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public BigDecimal getnCodseguro() {
        return nCodseguro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_SEGURO.N_CODSEGURO
     *
     * @param nCodseguro the value for SIMINTRA1.SITB_SEGURO.N_CODSEGURO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public void setnCodseguro(BigDecimal nCodseguro) {
        this.nCodseguro = nCodseguro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_SEGURO.V_DESSEGURO
     *
     * @return the value of SIMINTRA1.SITB_SEGURO.V_DESSEGURO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public String getvDesseguro() {
        return vDesseguro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_SEGURO.V_DESSEGURO
     *
     * @param vDesseguro the value for SIMINTRA1.SITB_SEGURO.V_DESSEGURO
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public void setvDesseguro(String vDesseguro) {
        this.vDesseguro = vDesseguro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_SEGURO.V_FLGACT
     *
     * @return the value of SIMINTRA1.SITB_SEGURO.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public String getvFlgact() {
        return vFlgact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_SEGURO.V_FLGACT
     *
     * @param vFlgact the value for SIMINTRA1.SITB_SEGURO.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public void setvFlgact(String vFlgact) {
        this.vFlgact = vFlgact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_SEGURO.N_CORTIPSEG
     *
     * @return the value of SIMINTRA1.SITB_SEGURO.N_CORTIPSEG
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public BigDecimal getnCortipseg() {
        return nCortipseg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_SEGURO.N_CORTIPSEG
     *
     * @param nCortipseg the value for SIMINTRA1.SITB_SEGURO.N_CORTIPSEG
     *
     * @mbggenerated Thu Mar 30 08:50:03 COT 2017
     */
    public void setnCortipseg(BigDecimal nCortipseg) {
        this.nCortipseg = nCortipseg;
    }
}