package pe.gob.sunafil.gestionpersonal.persistence.model;

import java.math.BigDecimal;
import java.util.Date;

public class VstRegpensionario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.N_CORPERREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private BigDecimal nCorperregpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.V_CODPERSONAL
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private String vCodpersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.N_CODREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private BigDecimal nCodregpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.D_FECINI
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private Date dFecini;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.D_FECFIN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private Date dFecfin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private String vFlgact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.V_CODUSUREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private String vCodusureg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.D_FECREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private Date dFecreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.V_HOSTREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private String vHostreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.V_CODUSUMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private String vCodusumod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.D_FECMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private Date dFecmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.V_HOSTMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private String vHostmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_REGPENSIONARIO.V_DESREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    private String vDesregpen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.N_CORPERREGPEN
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.N_CORPERREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public BigDecimal getnCorperregpen() {
        return nCorperregpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.N_CORPERREGPEN
     *
     * @param nCorperregpen the value for RRHHSYS.VST_REGPENSIONARIO.N_CORPERREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setnCorperregpen(BigDecimal nCorperregpen) {
        this.nCorperregpen = nCorperregpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_CODPERSONAL
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.V_CODPERSONAL
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public String getvCodpersonal() {
        return vCodpersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_CODPERSONAL
     *
     * @param vCodpersonal the value for RRHHSYS.VST_REGPENSIONARIO.V_CODPERSONAL
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setvCodpersonal(String vCodpersonal) {
        this.vCodpersonal = vCodpersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.N_CODREGPEN
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.N_CODREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public BigDecimal getnCodregpen() {
        return nCodregpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.N_CODREGPEN
     *
     * @param nCodregpen the value for RRHHSYS.VST_REGPENSIONARIO.N_CODREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setnCodregpen(BigDecimal nCodregpen) {
        this.nCodregpen = nCodregpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.D_FECINI
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.D_FECINI
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public Date getdFecini() {
        return dFecini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.D_FECINI
     *
     * @param dFecini the value for RRHHSYS.VST_REGPENSIONARIO.D_FECINI
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setdFecini(Date dFecini) {
        this.dFecini = dFecini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.D_FECFIN
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.D_FECFIN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public Date getdFecfin() {
        return dFecfin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.D_FECFIN
     *
     * @param dFecfin the value for RRHHSYS.VST_REGPENSIONARIO.D_FECFIN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setdFecfin(Date dFecfin) {
        this.dFecfin = dFecfin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_FLGACT
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public String getvFlgact() {
        return vFlgact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_FLGACT
     *
     * @param vFlgact the value for RRHHSYS.VST_REGPENSIONARIO.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setvFlgact(String vFlgact) {
        this.vFlgact = vFlgact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_CODUSUREG
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.V_CODUSUREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public String getvCodusureg() {
        return vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_CODUSUREG
     *
     * @param vCodusureg the value for RRHHSYS.VST_REGPENSIONARIO.V_CODUSUREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setvCodusureg(String vCodusureg) {
        this.vCodusureg = vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.D_FECREG
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.D_FECREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public Date getdFecreg() {
        return dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.D_FECREG
     *
     * @param dFecreg the value for RRHHSYS.VST_REGPENSIONARIO.D_FECREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setdFecreg(Date dFecreg) {
        this.dFecreg = dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_HOSTREG
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.V_HOSTREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public String getvHostreg() {
        return vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_HOSTREG
     *
     * @param vHostreg the value for RRHHSYS.VST_REGPENSIONARIO.V_HOSTREG
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setvHostreg(String vHostreg) {
        this.vHostreg = vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_CODUSUMOD
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.V_CODUSUMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public String getvCodusumod() {
        return vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_CODUSUMOD
     *
     * @param vCodusumod the value for RRHHSYS.VST_REGPENSIONARIO.V_CODUSUMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setvCodusumod(String vCodusumod) {
        this.vCodusumod = vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.D_FECMOD
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.D_FECMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public Date getdFecmod() {
        return dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.D_FECMOD
     *
     * @param dFecmod the value for RRHHSYS.VST_REGPENSIONARIO.D_FECMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setdFecmod(Date dFecmod) {
        this.dFecmod = dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_HOSTMOD
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.V_HOSTMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public String getvHostmod() {
        return vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_HOSTMOD
     *
     * @param vHostmod the value for RRHHSYS.VST_REGPENSIONARIO.V_HOSTMOD
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setvHostmod(String vHostmod) {
        this.vHostmod = vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_DESREGPEN
     *
     * @return the value of RRHHSYS.VST_REGPENSIONARIO.V_DESREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public String getvDesregpen() {
        return vDesregpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_REGPENSIONARIO.V_DESREGPEN
     *
     * @param vDesregpen the value for RRHHSYS.VST_REGPENSIONARIO.V_DESREGPEN
     *
     * @mbggenerated Thu Mar 30 08:50:04 COT 2017
     */
    public void setvDesregpen(String vDesregpen) {
        this.vDesregpen = vDesregpen;
    }
}