package pe.gob.sunafil.postulacioncas.persistence.model;

public class SitbPersonaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_PERSONA.V_NUMDOC
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    private String vNumdoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_PERSONA.V_CODTDOCIDE
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    private String vCodtdocide;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_PERSONA.V_NUMDOC
     *
     * @return the value of SIMINTRA1.SITB_PERSONA.V_NUMDOC
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    public String getvNumdoc() {
        return vNumdoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_PERSONA.V_NUMDOC
     *
     * @param vNumdoc the value for SIMINTRA1.SITB_PERSONA.V_NUMDOC
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    public void setvNumdoc(String vNumdoc) {
        this.vNumdoc = vNumdoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_PERSONA.V_CODTDOCIDE
     *
     * @return the value of SIMINTRA1.SITB_PERSONA.V_CODTDOCIDE
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    public String getvCodtdocide() {
        return vCodtdocide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_PERSONA.V_CODTDOCIDE
     *
     * @param vCodtdocide the value for SIMINTRA1.SITB_PERSONA.V_CODTDOCIDE
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    public void setvCodtdocide(String vCodtdocide) {
        this.vCodtdocide = vCodtdocide;
    }
}