package pe.gob.sunafil.denunciavirtual.persistence.model;

import java.math.BigDecimal;
import java.util.Date;

public class DlmvSolicitud {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.N_CODSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private BigDecimal nCodsol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODTDOCIDE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCodtdocide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMDOC
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vNumdoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCodemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCoddepemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODPROEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCodproemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDISEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCoddisemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_DIREMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vDiremp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_DIRPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vDirper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCoddepper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODPROPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCodproper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDISPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCoddisper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_TELFIJO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vTelfijo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_TELCEL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vTelcel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_EMAIL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_FLGRELLAB
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vFlgrellab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECING
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private Date dFecing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECCES
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private Date dFecces;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CARGO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCargo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODTMON
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCodtmon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.N_MONTO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private BigDecimal nMonto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.N_CODMAT
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private BigDecimal nCodmat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_DESOTROS
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vDesotros;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_MOTIVO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vMotivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMHOJA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vNumhoja;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_ANHOHOJA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vAnhohoja;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.N_FLGEST
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private BigDecimal nFlgest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vNumsol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_ANHOSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vAnhosol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_FLGRES
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vFlgres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCodusureg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private Date dFecreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_HOSTREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vHostreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vCodusumod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private Date dFecmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DENVIRTUAL.DLMV_SOLICITUD.V_HOSTMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    private String vHostmod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.N_CODSOL
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.N_CODSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public BigDecimal getnCodsol() {
        return nCodsol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.N_CODSOL
     *
     * @param nCodsol the value for DENVIRTUAL.DLMV_SOLICITUD.N_CODSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setnCodsol(BigDecimal nCodsol) {
        this.nCodsol = nCodsol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODTDOCIDE
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODTDOCIDE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCodtdocide() {
        return vCodtdocide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODTDOCIDE
     *
     * @param vCodtdocide the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODTDOCIDE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCodtdocide(String vCodtdocide) {
        this.vCodtdocide = vCodtdocide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMDOC
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_NUMDOC
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvNumdoc() {
        return vNumdoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMDOC
     *
     * @param vNumdoc the value for DENVIRTUAL.DLMV_SOLICITUD.V_NUMDOC
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvNumdoc(String vNumdoc) {
        this.vNumdoc = vNumdoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODEMP
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCodemp() {
        return vCodemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODEMP
     *
     * @param vCodemp the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCodemp(String vCodemp) {
        this.vCodemp = vCodemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPEMP
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCoddepemp() {
        return vCoddepemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPEMP
     *
     * @param vCoddepemp the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCoddepemp(String vCoddepemp) {
        this.vCoddepemp = vCoddepemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODPROEMP
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODPROEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCodproemp() {
        return vCodproemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODPROEMP
     *
     * @param vCodproemp the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODPROEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCodproemp(String vCodproemp) {
        this.vCodproemp = vCodproemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDISEMP
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODDISEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCoddisemp() {
        return vCoddisemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDISEMP
     *
     * @param vCoddisemp the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODDISEMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCoddisemp(String vCoddisemp) {
        this.vCoddisemp = vCoddisemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_DIREMP
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_DIREMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvDiremp() {
        return vDiremp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_DIREMP
     *
     * @param vDiremp the value for DENVIRTUAL.DLMV_SOLICITUD.V_DIREMP
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvDiremp(String vDiremp) {
        this.vDiremp = vDiremp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_DIRPER
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_DIRPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvDirper() {
        return vDirper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_DIRPER
     *
     * @param vDirper the value for DENVIRTUAL.DLMV_SOLICITUD.V_DIRPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvDirper(String vDirper) {
        this.vDirper = vDirper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPPER
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCoddepper() {
        return vCoddepper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPPER
     *
     * @param vCoddepper the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODDEPPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCoddepper(String vCoddepper) {
        this.vCoddepper = vCoddepper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODPROPER
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODPROPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCodproper() {
        return vCodproper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODPROPER
     *
     * @param vCodproper the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODPROPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCodproper(String vCodproper) {
        this.vCodproper = vCodproper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDISPER
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODDISPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCoddisper() {
        return vCoddisper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODDISPER
     *
     * @param vCoddisper the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODDISPER
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCoddisper(String vCoddisper) {
        this.vCoddisper = vCoddisper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_TELFIJO
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_TELFIJO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvTelfijo() {
        return vTelfijo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_TELFIJO
     *
     * @param vTelfijo the value for DENVIRTUAL.DLMV_SOLICITUD.V_TELFIJO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvTelfijo(String vTelfijo) {
        this.vTelfijo = vTelfijo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_TELCEL
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_TELCEL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvTelcel() {
        return vTelcel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_TELCEL
     *
     * @param vTelcel the value for DENVIRTUAL.DLMV_SOLICITUD.V_TELCEL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvTelcel(String vTelcel) {
        this.vTelcel = vTelcel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_EMAIL
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_EMAIL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvEmail() {
        return vEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_EMAIL
     *
     * @param vEmail the value for DENVIRTUAL.DLMV_SOLICITUD.V_EMAIL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvEmail(String vEmail) {
        this.vEmail = vEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_FLGRELLAB
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_FLGRELLAB
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvFlgrellab() {
        return vFlgrellab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_FLGRELLAB
     *
     * @param vFlgrellab the value for DENVIRTUAL.DLMV_SOLICITUD.V_FLGRELLAB
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvFlgrellab(String vFlgrellab) {
        this.vFlgrellab = vFlgrellab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECING
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.D_FECING
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public Date getdFecing() {
        return dFecing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECING
     *
     * @param dFecing the value for DENVIRTUAL.DLMV_SOLICITUD.D_FECING
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setdFecing(Date dFecing) {
        this.dFecing = dFecing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECCES
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.D_FECCES
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public Date getdFecces() {
        return dFecces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECCES
     *
     * @param dFecces the value for DENVIRTUAL.DLMV_SOLICITUD.D_FECCES
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setdFecces(Date dFecces) {
        this.dFecces = dFecces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CARGO
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CARGO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCargo() {
        return vCargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CARGO
     *
     * @param vCargo the value for DENVIRTUAL.DLMV_SOLICITUD.V_CARGO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCargo(String vCargo) {
        this.vCargo = vCargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODTMON
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODTMON
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCodtmon() {
        return vCodtmon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODTMON
     *
     * @param vCodtmon the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODTMON
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCodtmon(String vCodtmon) {
        this.vCodtmon = vCodtmon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.N_MONTO
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.N_MONTO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public BigDecimal getnMonto() {
        return nMonto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.N_MONTO
     *
     * @param nMonto the value for DENVIRTUAL.DLMV_SOLICITUD.N_MONTO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setnMonto(BigDecimal nMonto) {
        this.nMonto = nMonto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.N_CODMAT
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.N_CODMAT
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public BigDecimal getnCodmat() {
        return nCodmat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.N_CODMAT
     *
     * @param nCodmat the value for DENVIRTUAL.DLMV_SOLICITUD.N_CODMAT
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setnCodmat(BigDecimal nCodmat) {
        this.nCodmat = nCodmat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_DESOTROS
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_DESOTROS
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvDesotros() {
        return vDesotros;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_DESOTROS
     *
     * @param vDesotros the value for DENVIRTUAL.DLMV_SOLICITUD.V_DESOTROS
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvDesotros(String vDesotros) {
        this.vDesotros = vDesotros;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_MOTIVO
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_MOTIVO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvMotivo() {
        return vMotivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_MOTIVO
     *
     * @param vMotivo the value for DENVIRTUAL.DLMV_SOLICITUD.V_MOTIVO
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvMotivo(String vMotivo) {
        this.vMotivo = vMotivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMHOJA
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_NUMHOJA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvNumhoja() {
        return vNumhoja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMHOJA
     *
     * @param vNumhoja the value for DENVIRTUAL.DLMV_SOLICITUD.V_NUMHOJA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvNumhoja(String vNumhoja) {
        this.vNumhoja = vNumhoja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_ANHOHOJA
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_ANHOHOJA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvAnhohoja() {
        return vAnhohoja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_ANHOHOJA
     *
     * @param vAnhohoja the value for DENVIRTUAL.DLMV_SOLICITUD.V_ANHOHOJA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvAnhohoja(String vAnhohoja) {
        this.vAnhohoja = vAnhohoja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.N_FLGEST
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.N_FLGEST
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public BigDecimal getnFlgest() {
        return nFlgest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.N_FLGEST
     *
     * @param nFlgest the value for DENVIRTUAL.DLMV_SOLICITUD.N_FLGEST
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setnFlgest(BigDecimal nFlgest) {
        this.nFlgest = nFlgest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMSOL
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_NUMSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvNumsol() {
        return vNumsol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_NUMSOL
     *
     * @param vNumsol the value for DENVIRTUAL.DLMV_SOLICITUD.V_NUMSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvNumsol(String vNumsol) {
        this.vNumsol = vNumsol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_ANHOSOL
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_ANHOSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvAnhosol() {
        return vAnhosol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_ANHOSOL
     *
     * @param vAnhosol the value for DENVIRTUAL.DLMV_SOLICITUD.V_ANHOSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvAnhosol(String vAnhosol) {
        this.vAnhosol = vAnhosol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_FLGRES
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_FLGRES
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvFlgres() {
        return vFlgres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_FLGRES
     *
     * @param vFlgres the value for DENVIRTUAL.DLMV_SOLICITUD.V_FLGRES
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvFlgres(String vFlgres) {
        this.vFlgres = vFlgres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUREG
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCodusureg() {
        return vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUREG
     *
     * @param vCodusureg the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCodusureg(String vCodusureg) {
        this.vCodusureg = vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECREG
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.D_FECREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public Date getdFecreg() {
        return dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECREG
     *
     * @param dFecreg the value for DENVIRTUAL.DLMV_SOLICITUD.D_FECREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setdFecreg(Date dFecreg) {
        this.dFecreg = dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_HOSTREG
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_HOSTREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvHostreg() {
        return vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_HOSTREG
     *
     * @param vHostreg the value for DENVIRTUAL.DLMV_SOLICITUD.V_HOSTREG
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvHostreg(String vHostreg) {
        this.vHostreg = vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUMOD
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvCodusumod() {
        return vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUMOD
     *
     * @param vCodusumod the value for DENVIRTUAL.DLMV_SOLICITUD.V_CODUSUMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvCodusumod(String vCodusumod) {
        this.vCodusumod = vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECMOD
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.D_FECMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public Date getdFecmod() {
        return dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.D_FECMOD
     *
     * @param dFecmod the value for DENVIRTUAL.DLMV_SOLICITUD.D_FECMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setdFecmod(Date dFecmod) {
        this.dFecmod = dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_HOSTMOD
     *
     * @return the value of DENVIRTUAL.DLMV_SOLICITUD.V_HOSTMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public String getvHostmod() {
        return vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DENVIRTUAL.DLMV_SOLICITUD.V_HOSTMOD
     *
     * @param vHostmod the value for DENVIRTUAL.DLMV_SOLICITUD.V_HOSTMOD
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    public void setvHostmod(String vHostmod) {
        this.vHostmod = vHostmod;
    }
}