package pe.gob.sunafil.gestionpersonal.persistence.model;

import java.math.BigDecimal;
import java.util.Date;

public class RhtbdPersonal extends RhtbdPersonalKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.N_NUMDEP
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private Short nNumdep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_CODCARGO
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vCodcargo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_CODESCALA
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vCodescala;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_CODTIPO
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vCodtipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_FLGPRIN
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vFlgprin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vFlgact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.D_FECINI
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private Date dFecini;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.D_FECFIN
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private Date dFecfin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_CODUSUREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vCodusureg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.D_FECREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private Date dFecreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_HOSTREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vHostreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_CODUSUMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vCodusumod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.D_FECMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private Date dFecmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_HOSTMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vHostmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_NUMCON
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vNumcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_ANOCON
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vAnocon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.N_REMUNERA
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private BigDecimal nRemunera;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_NUMCONVOC
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vNumconvoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_ANOCONVOC
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vAnoconvoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.N_CODRES
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private BigDecimal nCodres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.V_FLGDES
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private String vFlgdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBD_PERSONAL.N_CORCLACAR
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    private BigDecimal nCorclacar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.N_NUMDEP
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.N_NUMDEP
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public Short getnNumdep() {
        return nNumdep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.N_NUMDEP
     *
     * @param nNumdep the value for RRHHSYS.RHTBD_PERSONAL.N_NUMDEP
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setnNumdep(Short nNumdep) {
        this.nNumdep = nNumdep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODCARGO
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_CODCARGO
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvCodcargo() {
        return vCodcargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODCARGO
     *
     * @param vCodcargo the value for RRHHSYS.RHTBD_PERSONAL.V_CODCARGO
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvCodcargo(String vCodcargo) {
        this.vCodcargo = vCodcargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODESCALA
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_CODESCALA
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvCodescala() {
        return vCodescala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODESCALA
     *
     * @param vCodescala the value for RRHHSYS.RHTBD_PERSONAL.V_CODESCALA
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvCodescala(String vCodescala) {
        this.vCodescala = vCodescala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODTIPO
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_CODTIPO
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvCodtipo() {
        return vCodtipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODTIPO
     *
     * @param vCodtipo the value for RRHHSYS.RHTBD_PERSONAL.V_CODTIPO
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvCodtipo(String vCodtipo) {
        this.vCodtipo = vCodtipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_FLGPRIN
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_FLGPRIN
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvFlgprin() {
        return vFlgprin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_FLGPRIN
     *
     * @param vFlgprin the value for RRHHSYS.RHTBD_PERSONAL.V_FLGPRIN
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvFlgprin(String vFlgprin) {
        this.vFlgprin = vFlgprin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_FLGACT
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvFlgact() {
        return vFlgact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_FLGACT
     *
     * @param vFlgact the value for RRHHSYS.RHTBD_PERSONAL.V_FLGACT
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvFlgact(String vFlgact) {
        this.vFlgact = vFlgact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.D_FECINI
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.D_FECINI
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public Date getdFecini() {
        return dFecini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.D_FECINI
     *
     * @param dFecini the value for RRHHSYS.RHTBD_PERSONAL.D_FECINI
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setdFecini(Date dFecini) {
        this.dFecini = dFecini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.D_FECFIN
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.D_FECFIN
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public Date getdFecfin() {
        return dFecfin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.D_FECFIN
     *
     * @param dFecfin the value for RRHHSYS.RHTBD_PERSONAL.D_FECFIN
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setdFecfin(Date dFecfin) {
        this.dFecfin = dFecfin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODUSUREG
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_CODUSUREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvCodusureg() {
        return vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODUSUREG
     *
     * @param vCodusureg the value for RRHHSYS.RHTBD_PERSONAL.V_CODUSUREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvCodusureg(String vCodusureg) {
        this.vCodusureg = vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.D_FECREG
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.D_FECREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public Date getdFecreg() {
        return dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.D_FECREG
     *
     * @param dFecreg the value for RRHHSYS.RHTBD_PERSONAL.D_FECREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setdFecreg(Date dFecreg) {
        this.dFecreg = dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_HOSTREG
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_HOSTREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvHostreg() {
        return vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_HOSTREG
     *
     * @param vHostreg the value for RRHHSYS.RHTBD_PERSONAL.V_HOSTREG
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvHostreg(String vHostreg) {
        this.vHostreg = vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODUSUMOD
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_CODUSUMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvCodusumod() {
        return vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_CODUSUMOD
     *
     * @param vCodusumod the value for RRHHSYS.RHTBD_PERSONAL.V_CODUSUMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvCodusumod(String vCodusumod) {
        this.vCodusumod = vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.D_FECMOD
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.D_FECMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public Date getdFecmod() {
        return dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.D_FECMOD
     *
     * @param dFecmod the value for RRHHSYS.RHTBD_PERSONAL.D_FECMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setdFecmod(Date dFecmod) {
        this.dFecmod = dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_HOSTMOD
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_HOSTMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvHostmod() {
        return vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_HOSTMOD
     *
     * @param vHostmod the value for RRHHSYS.RHTBD_PERSONAL.V_HOSTMOD
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvHostmod(String vHostmod) {
        this.vHostmod = vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_NUMCON
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_NUMCON
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvNumcon() {
        return vNumcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_NUMCON
     *
     * @param vNumcon the value for RRHHSYS.RHTBD_PERSONAL.V_NUMCON
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvNumcon(String vNumcon) {
        this.vNumcon = vNumcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_ANOCON
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_ANOCON
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvAnocon() {
        return vAnocon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_ANOCON
     *
     * @param vAnocon the value for RRHHSYS.RHTBD_PERSONAL.V_ANOCON
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvAnocon(String vAnocon) {
        this.vAnocon = vAnocon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.N_REMUNERA
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.N_REMUNERA
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public BigDecimal getnRemunera() {
        return nRemunera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.N_REMUNERA
     *
     * @param nRemunera the value for RRHHSYS.RHTBD_PERSONAL.N_REMUNERA
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setnRemunera(BigDecimal nRemunera) {
        this.nRemunera = nRemunera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_NUMCONVOC
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_NUMCONVOC
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvNumconvoc() {
        return vNumconvoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_NUMCONVOC
     *
     * @param vNumconvoc the value for RRHHSYS.RHTBD_PERSONAL.V_NUMCONVOC
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvNumconvoc(String vNumconvoc) {
        this.vNumconvoc = vNumconvoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_ANOCONVOC
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_ANOCONVOC
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvAnoconvoc() {
        return vAnoconvoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_ANOCONVOC
     *
     * @param vAnoconvoc the value for RRHHSYS.RHTBD_PERSONAL.V_ANOCONVOC
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvAnoconvoc(String vAnoconvoc) {
        this.vAnoconvoc = vAnoconvoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.N_CODRES
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.N_CODRES
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public BigDecimal getnCodres() {
        return nCodres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.N_CODRES
     *
     * @param nCodres the value for RRHHSYS.RHTBD_PERSONAL.N_CODRES
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setnCodres(BigDecimal nCodres) {
        this.nCodres = nCodres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.V_FLGDES
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.V_FLGDES
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public String getvFlgdes() {
        return vFlgdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.V_FLGDES
     *
     * @param vFlgdes the value for RRHHSYS.RHTBD_PERSONAL.V_FLGDES
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setvFlgdes(String vFlgdes) {
        this.vFlgdes = vFlgdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBD_PERSONAL.N_CORCLACAR
     *
     * @return the value of RRHHSYS.RHTBD_PERSONAL.N_CORCLACAR
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public BigDecimal getnCorclacar() {
        return nCorclacar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBD_PERSONAL.N_CORCLACAR
     *
     * @param nCorclacar the value for RRHHSYS.RHTBD_PERSONAL.N_CORCLACAR
     *
     * @mbggenerated Thu Mar 30 08:32:05 COT 2017
     */
    public void setnCorclacar(BigDecimal nCorclacar) {
        this.nCorclacar = nCorclacar;
    }
}