package pe.gob.sunafil.gestionpersonal.persistence.model;

import java.math.BigDecimal;
import java.util.Date;

public class VstDirecciones {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.N_CORPERDIR
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private BigDecimal nCorperdir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_CODPERSONAL
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vCodpersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_CODDEP
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vCoddep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_CODPRO
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vCodpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_CODDIS
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vCoddis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_CODZON
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vCodzon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_DESZONA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vDeszona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_CODTVIA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vCodtvia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_DIRECCION
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vDireccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_CODUSUREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vCodusureg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.D_FECREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private Date dFecreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_HOSTREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vHostreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_CODUSUMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vCodusumod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.D_FECMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private Date dFecmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_HOSTMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vHostmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_FLGDIRULT
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vFlgdirult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_DESDIS
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vDesdis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_DESZON
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vDeszon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_DIRECCIONES.V_DESTVIA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    private String vDestvia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.N_CORPERDIR
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.N_CORPERDIR
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public BigDecimal getnCorperdir() {
        return nCorperdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.N_CORPERDIR
     *
     * @param nCorperdir the value for RRHHSYS.VST_DIRECCIONES.N_CORPERDIR
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setnCorperdir(BigDecimal nCorperdir) {
        this.nCorperdir = nCorperdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODPERSONAL
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_CODPERSONAL
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvCodpersonal() {
        return vCodpersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODPERSONAL
     *
     * @param vCodpersonal the value for RRHHSYS.VST_DIRECCIONES.V_CODPERSONAL
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvCodpersonal(String vCodpersonal) {
        this.vCodpersonal = vCodpersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODDEP
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_CODDEP
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvCoddep() {
        return vCoddep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODDEP
     *
     * @param vCoddep the value for RRHHSYS.VST_DIRECCIONES.V_CODDEP
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvCoddep(String vCoddep) {
        this.vCoddep = vCoddep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODPRO
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_CODPRO
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvCodpro() {
        return vCodpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODPRO
     *
     * @param vCodpro the value for RRHHSYS.VST_DIRECCIONES.V_CODPRO
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvCodpro(String vCodpro) {
        this.vCodpro = vCodpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODDIS
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_CODDIS
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvCoddis() {
        return vCoddis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODDIS
     *
     * @param vCoddis the value for RRHHSYS.VST_DIRECCIONES.V_CODDIS
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvCoddis(String vCoddis) {
        this.vCoddis = vCoddis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODZON
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_CODZON
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvCodzon() {
        return vCodzon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODZON
     *
     * @param vCodzon the value for RRHHSYS.VST_DIRECCIONES.V_CODZON
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvCodzon(String vCodzon) {
        this.vCodzon = vCodzon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_DESZONA
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_DESZONA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvDeszona() {
        return vDeszona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_DESZONA
     *
     * @param vDeszona the value for RRHHSYS.VST_DIRECCIONES.V_DESZONA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvDeszona(String vDeszona) {
        this.vDeszona = vDeszona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODTVIA
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_CODTVIA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvCodtvia() {
        return vCodtvia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODTVIA
     *
     * @param vCodtvia the value for RRHHSYS.VST_DIRECCIONES.V_CODTVIA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvCodtvia(String vCodtvia) {
        this.vCodtvia = vCodtvia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_DIRECCION
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_DIRECCION
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvDireccion() {
        return vDireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_DIRECCION
     *
     * @param vDireccion the value for RRHHSYS.VST_DIRECCIONES.V_DIRECCION
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvDireccion(String vDireccion) {
        this.vDireccion = vDireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODUSUREG
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_CODUSUREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvCodusureg() {
        return vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODUSUREG
     *
     * @param vCodusureg the value for RRHHSYS.VST_DIRECCIONES.V_CODUSUREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvCodusureg(String vCodusureg) {
        this.vCodusureg = vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.D_FECREG
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.D_FECREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public Date getdFecreg() {
        return dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.D_FECREG
     *
     * @param dFecreg the value for RRHHSYS.VST_DIRECCIONES.D_FECREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setdFecreg(Date dFecreg) {
        this.dFecreg = dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_HOSTREG
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_HOSTREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvHostreg() {
        return vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_HOSTREG
     *
     * @param vHostreg the value for RRHHSYS.VST_DIRECCIONES.V_HOSTREG
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvHostreg(String vHostreg) {
        this.vHostreg = vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODUSUMOD
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_CODUSUMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvCodusumod() {
        return vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_CODUSUMOD
     *
     * @param vCodusumod the value for RRHHSYS.VST_DIRECCIONES.V_CODUSUMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvCodusumod(String vCodusumod) {
        this.vCodusumod = vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.D_FECMOD
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.D_FECMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public Date getdFecmod() {
        return dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.D_FECMOD
     *
     * @param dFecmod the value for RRHHSYS.VST_DIRECCIONES.D_FECMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setdFecmod(Date dFecmod) {
        this.dFecmod = dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_HOSTMOD
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_HOSTMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvHostmod() {
        return vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_HOSTMOD
     *
     * @param vHostmod the value for RRHHSYS.VST_DIRECCIONES.V_HOSTMOD
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvHostmod(String vHostmod) {
        this.vHostmod = vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_FLGDIRULT
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_FLGDIRULT
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvFlgdirult() {
        return vFlgdirult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_FLGDIRULT
     *
     * @param vFlgdirult the value for RRHHSYS.VST_DIRECCIONES.V_FLGDIRULT
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvFlgdirult(String vFlgdirult) {
        this.vFlgdirult = vFlgdirult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_DESDIS
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_DESDIS
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvDesdis() {
        return vDesdis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_DESDIS
     *
     * @param vDesdis the value for RRHHSYS.VST_DIRECCIONES.V_DESDIS
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvDesdis(String vDesdis) {
        this.vDesdis = vDesdis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_DESZON
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_DESZON
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvDeszon() {
        return vDeszon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_DESZON
     *
     * @param vDeszon the value for RRHHSYS.VST_DIRECCIONES.V_DESZON
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvDeszon(String vDeszon) {
        this.vDeszon = vDeszon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_DIRECCIONES.V_DESTVIA
     *
     * @return the value of RRHHSYS.VST_DIRECCIONES.V_DESTVIA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public String getvDestvia() {
        return vDestvia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_DIRECCIONES.V_DESTVIA
     *
     * @param vDestvia the value for RRHHSYS.VST_DIRECCIONES.V_DESTVIA
     *
     * @mbggenerated Wed Mar 22 17:19:40 COT 2017
     */
    public void setvDestvia(String vDestvia) {
        this.vDestvia = vDestvia;
    }
}