package pe.gob.sunafil.gestionpersonal.persistence.model;

import java.math.BigDecimal;
import java.util.Date;

public class VstTiporesolucion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.N_CODRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private BigDecimal nCodres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.N_CORTIPRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private BigDecimal nCortipres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.V_NUMRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private String vNumres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.V_ANORES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private String vAnores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.D_FECINI
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private Date dFecini;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.D_FECFIN
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private Date dFecfin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.V_NOMARCHIV
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private String vNomarchiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.V_DESTIPRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private String vDestipres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.VST_TIPORESOLUCION.V_FLGACT
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    private String vFlgact;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.N_CODRES
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.N_CODRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public BigDecimal getnCodres() {
        return nCodres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.N_CODRES
     *
     * @param nCodres the value for RRHHSYS.VST_TIPORESOLUCION.N_CODRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setnCodres(BigDecimal nCodres) {
        this.nCodres = nCodres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.N_CORTIPRES
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.N_CORTIPRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public BigDecimal getnCortipres() {
        return nCortipres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.N_CORTIPRES
     *
     * @param nCortipres the value for RRHHSYS.VST_TIPORESOLUCION.N_CORTIPRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setnCortipres(BigDecimal nCortipres) {
        this.nCortipres = nCortipres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_NUMRES
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.V_NUMRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public String getvNumres() {
        return vNumres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_NUMRES
     *
     * @param vNumres the value for RRHHSYS.VST_TIPORESOLUCION.V_NUMRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setvNumres(String vNumres) {
        this.vNumres = vNumres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_ANORES
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.V_ANORES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public String getvAnores() {
        return vAnores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_ANORES
     *
     * @param vAnores the value for RRHHSYS.VST_TIPORESOLUCION.V_ANORES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setvAnores(String vAnores) {
        this.vAnores = vAnores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.D_FECINI
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.D_FECINI
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public Date getdFecini() {
        return dFecini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.D_FECINI
     *
     * @param dFecini the value for RRHHSYS.VST_TIPORESOLUCION.D_FECINI
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setdFecini(Date dFecini) {
        this.dFecini = dFecini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.D_FECFIN
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.D_FECFIN
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public Date getdFecfin() {
        return dFecfin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.D_FECFIN
     *
     * @param dFecfin the value for RRHHSYS.VST_TIPORESOLUCION.D_FECFIN
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setdFecfin(Date dFecfin) {
        this.dFecfin = dFecfin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_NOMARCHIV
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.V_NOMARCHIV
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public String getvNomarchiv() {
        return vNomarchiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_NOMARCHIV
     *
     * @param vNomarchiv the value for RRHHSYS.VST_TIPORESOLUCION.V_NOMARCHIV
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setvNomarchiv(String vNomarchiv) {
        this.vNomarchiv = vNomarchiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_DESTIPRES
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.V_DESTIPRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public String getvDestipres() {
        return vDestipres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_DESTIPRES
     *
     * @param vDestipres the value for RRHHSYS.VST_TIPORESOLUCION.V_DESTIPRES
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setvDestipres(String vDestipres) {
        this.vDestipres = vDestipres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_FLGACT
     *
     * @return the value of RRHHSYS.VST_TIPORESOLUCION.V_FLGACT
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public String getvFlgact() {
        return vFlgact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.VST_TIPORESOLUCION.V_FLGACT
     *
     * @param vFlgact the value for RRHHSYS.VST_TIPORESOLUCION.V_FLGACT
     *
     * @mbggenerated Wed Mar 29 15:54:11 COT 2017
     */
    public void setvFlgact(String vFlgact) {
        this.vFlgact = vFlgact;
    }
}