package pe.gob.sunafil.postulacioncas.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.postulacioncas.persistence.model.RhmvcHvxcapacitac;
import pe.gob.sunafil.postulacioncas.persistence.model.RhmvcHvxcapacitacExample;

public interface RhmvcHvxcapacitacMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int countByExample(RhmvcHvxcapacitacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int deleteByExample(RhmvcHvxcapacitacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int deleteByPrimaryKey(BigDecimal nCorhvcap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int insert(RhmvcHvxcapacitac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int insertSelective(RhmvcHvxcapacitac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    List<RhmvcHvxcapacitac> selectByExample(RhmvcHvxcapacitacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    RhmvcHvxcapacitac selectByPrimaryKey(BigDecimal nCorhvcap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int updateByExampleSelective(@Param("record") RhmvcHvxcapacitac record, @Param("example") RhmvcHvxcapacitacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int updateByExample(@Param("record") RhmvcHvxcapacitac record, @Param("example") RhmvcHvxcapacitacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int updateByPrimaryKeySelective(RhmvcHvxcapacitac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXCAPACITAC
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    int updateByPrimaryKey(RhmvcHvxcapacitac record);
}