package pe.gob.sunafil.tramiteext.persistence.model;

import java.util.Date;

public class TdtbcCorrelativo extends TdtbcCorrelativoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBC_CORRELATIVO.N_NUMULTIMO
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    private Long nNumultimo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUREG
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    private String vNomusureg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBC_CORRELATIVO.D_FECREG
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    private Date dFecreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUMOD
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    private String vNomusumod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBC_CORRELATIVO.D_FECMOD
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    private Date dFecmod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBC_CORRELATIVO.N_NUMULTIMO
     *
     * @return the value of TRAMITE.TDTBC_CORRELATIVO.N_NUMULTIMO
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public Long getnNumultimo() {
        return nNumultimo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBC_CORRELATIVO.N_NUMULTIMO
     *
     * @param nNumultimo the value for TRAMITE.TDTBC_CORRELATIVO.N_NUMULTIMO
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public void setnNumultimo(Long nNumultimo) {
        this.nNumultimo = nNumultimo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUREG
     *
     * @return the value of TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUREG
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public String getvNomusureg() {
        return vNomusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUREG
     *
     * @param vNomusureg the value for TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUREG
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public void setvNomusureg(String vNomusureg) {
        this.vNomusureg = vNomusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBC_CORRELATIVO.D_FECREG
     *
     * @return the value of TRAMITE.TDTBC_CORRELATIVO.D_FECREG
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public Date getdFecreg() {
        return dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBC_CORRELATIVO.D_FECREG
     *
     * @param dFecreg the value for TRAMITE.TDTBC_CORRELATIVO.D_FECREG
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public void setdFecreg(Date dFecreg) {
        this.dFecreg = dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUMOD
     *
     * @return the value of TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUMOD
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public String getvNomusumod() {
        return vNomusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUMOD
     *
     * @param vNomusumod the value for TRAMITE.TDTBC_CORRELATIVO.V_NOMUSUMOD
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public void setvNomusumod(String vNomusumod) {
        this.vNomusumod = vNomusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBC_CORRELATIVO.D_FECMOD
     *
     * @return the value of TRAMITE.TDTBC_CORRELATIVO.D_FECMOD
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public Date getdFecmod() {
        return dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBC_CORRELATIVO.D_FECMOD
     *
     * @param dFecmod the value for TRAMITE.TDTBC_CORRELATIVO.D_FECMOD
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public void setdFecmod(Date dFecmod) {
        this.dFecmod = dFecmod;
    }
}