package pe.gob.sunafil.denunciavirtual.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.denunciavirtual.persistence.model.SitbTipomoneda;
import pe.gob.sunafil.denunciavirtual.persistence.model.SitbTipomonedaExample;

public interface SitbTipomonedaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int countByExample(SitbTipomonedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int deleteByExample(SitbTipomonedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int deleteByPrimaryKey(String vCodtmon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int insert(SitbTipomoneda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int insertSelective(SitbTipomoneda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    List<SitbTipomoneda> selectByExample(SitbTipomonedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    SitbTipomoneda selectByPrimaryKey(String vCodtmon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByExampleSelective(@Param("record") SitbTipomoneda record, @Param("example") SitbTipomonedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByExample(@Param("record") SitbTipomoneda record, @Param("example") SitbTipomonedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByPrimaryKeySelective(SitbTipomoneda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_TIPOMONEDA
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByPrimaryKey(SitbTipomoneda record);
}