package pe.gob.sunafil.denunciavirtual.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.denunciavirtual.persistence.model.TdtbcTramite;
import pe.gob.sunafil.denunciavirtual.persistence.model.TdtbcTramiteExample;

public interface TdtbcTramiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int countByExample(TdtbcTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int deleteByExample(TdtbcTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int deleteByPrimaryKey(BigDecimal nCodtram);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int insert(TdtbcTramite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int insertSelective(TdtbcTramite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    List<TdtbcTramite> selectByExample(TdtbcTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    TdtbcTramite selectByPrimaryKey(BigDecimal nCodtram);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByExampleSelective(@Param("record") TdtbcTramite record, @Param("example") TdtbcTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByExample(@Param("record") TdtbcTramite record, @Param("example") TdtbcTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByPrimaryKeySelective(TdtbcTramite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_TRAMITE
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByPrimaryKey(TdtbcTramite record);
}