package pe.gob.sunafil.denunciavirtual.siit.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.denunciavirtual.siit.persistence.model.SitbEmpleador;
import pe.gob.sunafil.denunciavirtual.siit.persistence.model.SitbEmpleadorExample;

public interface SitbEmpleadorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int countByExample(SitbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int deleteByExample(SitbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int deleteByPrimaryKey(String vCodemp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int insert(SitbEmpleador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int insertSelective(SitbEmpleador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    List<SitbEmpleador> selectByExample(SitbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    SitbEmpleador selectByPrimaryKey(String vCodemp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int updateByExampleSelective(@Param("record") SitbEmpleador record, @Param("example") SitbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int updateByExample(@Param("record") SitbEmpleador record, @Param("example") SitbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int updateByPrimaryKeySelective(SitbEmpleador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_EMPLEADOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    int updateByPrimaryKey(SitbEmpleador record);
}