package pe.gob.sunafil.denunciavirtual.siit.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.denunciavirtual.siit.persistence.model.IltbcUnidad;
import pe.gob.sunafil.denunciavirtual.siit.persistence.model.IltbcUnidadExample;
import pe.gob.sunafil.denunciavirtual.siit.persistence.model.IltbcUnidadKey;

public interface IltbcUnidadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int countByExample(IltbcUnidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int deleteByExample(IltbcUnidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int deleteByPrimaryKey(IltbcUnidadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int insert(IltbcUnidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int insertSelective(IltbcUnidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    List<IltbcUnidad> selectByExample(IltbcUnidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    IltbcUnidad selectByPrimaryKey(IltbcUnidadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int updateByExampleSelective(@Param("record") IltbcUnidad record, @Param("example") IltbcUnidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int updateByExample(@Param("record") IltbcUnidad record, @Param("example") IltbcUnidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int updateByPrimaryKeySelective(IltbcUnidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.ILTBC_UNIDAD
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int updateByPrimaryKey(IltbcUnidad record);
}