package pe.gob.sunafil.denunciavirtual.siit.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.denunciavirtual.siit.persistence.model.VstIntendenRegionales;
import pe.gob.sunafil.denunciavirtual.siit.persistence.model.VstIntendenRegionalesExample;

public interface VstIntendenRegionalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_INTENDEN_REGIONALES
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int countByExample(VstIntendenRegionalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_INTENDEN_REGIONALES
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int deleteByExample(VstIntendenRegionalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_INTENDEN_REGIONALES
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int insert(VstIntendenRegionales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_INTENDEN_REGIONALES
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int insertSelective(VstIntendenRegionales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_INTENDEN_REGIONALES
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    List<VstIntendenRegionales> selectByExample(VstIntendenRegionalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_INTENDEN_REGIONALES
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int updateByExampleSelective(@Param("record") VstIntendenRegionales record, @Param("example") VstIntendenRegionalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_INTENDEN_REGIONALES
     *
     * @mbggenerated Tue Mar 07 17:22:30 COT 2017
     */
    int updateByExample(@Param("record") VstIntendenRegionales record, @Param("example") VstIntendenRegionalesExample example);
}