package pe.gob.sunafil.tramiteext.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.tramiteext.persistence.model.TdtbcCargocongres;
import pe.gob.sunafil.tramiteext.persistence.model.TdtbcCargocongresExample;

public interface TdtbcCargocongresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int countByExample(TdtbcCargocongresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int deleteByExample(TdtbcCargocongresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int deleteByPrimaryKey(BigDecimal nCodcarcon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int insert(TdtbcCargocongres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int insertSelective(TdtbcCargocongres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    List<TdtbcCargocongres> selectByExample(TdtbcCargocongresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    TdtbcCargocongres selectByPrimaryKey(BigDecimal nCodcarcon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") TdtbcCargocongres record, @Param("example") TdtbcCargocongresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int updateByExample(@Param("record") TdtbcCargocongres record, @Param("example") TdtbcCargocongresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int updateByPrimaryKeySelective(TdtbcCargocongres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_CARGOCONGRES
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int updateByPrimaryKey(TdtbcCargocongres record);
}