package pe.gob.sunafil.tramiteext.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.tramiteext.persistence.model.TdtbcGrupotupa;
import pe.gob.sunafil.tramiteext.persistence.model.TdtbcGrupotupaExample;

public interface TdtbcGrupotupaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int countByExample(TdtbcGrupotupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int deleteByExample(TdtbcGrupotupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int deleteByPrimaryKey(Short nNumgrupo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int insert(TdtbcGrupotupa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int insertSelective(TdtbcGrupotupa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    List<TdtbcGrupotupa> selectByExample(TdtbcGrupotupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    TdtbcGrupotupa selectByPrimaryKey(Short nNumgrupo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByExampleSelective(@Param("record") TdtbcGrupotupa record, @Param("example") TdtbcGrupotupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByExample(@Param("record") TdtbcGrupotupa record, @Param("example") TdtbcGrupotupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByPrimaryKeySelective(TdtbcGrupotupa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBC_GRUPOTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByPrimaryKey(TdtbcGrupotupa record);
}