package pe.gob.sunafil.tramiteext.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.tramiteext.persistence.model.TdtbdCentrolab;
import pe.gob.sunafil.tramiteext.persistence.model.TdtbdCentrolabExample;
import pe.gob.sunafil.tramiteext.persistence.model.TdtbdCentrolabKey;

public interface TdtbdCentrolabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int countByExample(TdtbdCentrolabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int deleteByExample(TdtbdCentrolabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int deleteByPrimaryKey(TdtbdCentrolabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int insert(TdtbdCentrolab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int insertSelective(TdtbdCentrolab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    List<TdtbdCentrolab> selectByExample(TdtbdCentrolabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    TdtbdCentrolab selectByPrimaryKey(TdtbdCentrolabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByExampleSelective(@Param("record") TdtbdCentrolab record, @Param("example") TdtbdCentrolabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByExample(@Param("record") TdtbdCentrolab record, @Param("example") TdtbdCentrolabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByPrimaryKeySelective(TdtbdCentrolab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDTBD_CENTROLAB
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByPrimaryKey(TdtbdCentrolab record);
}