package pe.gob.sunafil.tramiteext.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.tramiteext.persistence.model.TdmvdRegreqtupa;
import pe.gob.sunafil.tramiteext.persistence.model.TdmvdRegreqtupaExample;
import pe.gob.sunafil.tramiteext.persistence.model.TdmvdRegreqtupaKey;

public interface TdmvdRegreqtupaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int countByExample(TdmvdRegreqtupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int deleteByExample(TdmvdRegreqtupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int deleteByPrimaryKey(TdmvdRegreqtupaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int insert(TdmvdRegreqtupa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int insertSelective(TdmvdRegreqtupa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    List<TdmvdRegreqtupa> selectByExample(TdmvdRegreqtupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    TdmvdRegreqtupa selectByPrimaryKey(TdmvdRegreqtupaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByExampleSelective(@Param("record") TdmvdRegreqtupa record, @Param("example") TdmvdRegreqtupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByExample(@Param("record") TdmvdRegreqtupa record, @Param("example") TdmvdRegreqtupaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByPrimaryKeySelective(TdmvdRegreqtupa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVD_REGREQTUPA
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    int updateByPrimaryKey(TdmvdRegreqtupa record);
}