package pe.gob.sunafil.postulacioncas.persistence.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RhmvcExperienciaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public RhmvcExperienciaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andNCorexpIsNull() {
            addCriterion("N_COREXP is null");
            return (Criteria) this;
        }

        public Criteria andNCorexpIsNotNull() {
            addCriterion("N_COREXP is not null");
            return (Criteria) this;
        }

        public Criteria andNCorexpEqualTo(BigDecimal value) {
            addCriterion("N_COREXP =", value, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpNotEqualTo(BigDecimal value) {
            addCriterion("N_COREXP <>", value, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpGreaterThan(BigDecimal value) {
            addCriterion("N_COREXP >", value, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_COREXP >=", value, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpLessThan(BigDecimal value) {
            addCriterion("N_COREXP <", value, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_COREXP <=", value, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpIn(List<BigDecimal> values) {
            addCriterion("N_COREXP in", values, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpNotIn(List<BigDecimal> values) {
            addCriterion("N_COREXP not in", values, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_COREXP between", value1, value2, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorexpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_COREXP not between", value1, value2, "nCorexp");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidIsNull() {
            addCriterion("N_CORHOJVID is null");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidIsNotNull() {
            addCriterion("N_CORHOJVID is not null");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidEqualTo(BigDecimal value) {
            addCriterion("N_CORHOJVID =", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidNotEqualTo(BigDecimal value) {
            addCriterion("N_CORHOJVID <>", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidGreaterThan(BigDecimal value) {
            addCriterion("N_CORHOJVID >", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORHOJVID >=", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidLessThan(BigDecimal value) {
            addCriterion("N_CORHOJVID <", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORHOJVID <=", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidIn(List<BigDecimal> values) {
            addCriterion("N_CORHOJVID in", values, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidNotIn(List<BigDecimal> values) {
            addCriterion("N_CORHOJVID not in", values, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORHOJVID between", value1, value2, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORHOJVID not between", value1, value2, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andVEntidadIsNull() {
            addCriterion("V_ENTIDAD is null");
            return (Criteria) this;
        }

        public Criteria andVEntidadIsNotNull() {
            addCriterion("V_ENTIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andVEntidadEqualTo(String value) {
            addCriterion("V_ENTIDAD =", value, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadNotEqualTo(String value) {
            addCriterion("V_ENTIDAD <>", value, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadGreaterThan(String value) {
            addCriterion("V_ENTIDAD >", value, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadGreaterThanOrEqualTo(String value) {
            addCriterion("V_ENTIDAD >=", value, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadLessThan(String value) {
            addCriterion("V_ENTIDAD <", value, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadLessThanOrEqualTo(String value) {
            addCriterion("V_ENTIDAD <=", value, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadLike(String value) {
            addCriterion("V_ENTIDAD like", value, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadNotLike(String value) {
            addCriterion("V_ENTIDAD not like", value, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadIn(List<String> values) {
            addCriterion("V_ENTIDAD in", values, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadNotIn(List<String> values) {
            addCriterion("V_ENTIDAD not in", values, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadBetween(String value1, String value2) {
            addCriterion("V_ENTIDAD between", value1, value2, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVEntidadNotBetween(String value1, String value2) {
            addCriterion("V_ENTIDAD not between", value1, value2, "vEntidad");
            return (Criteria) this;
        }

        public Criteria andVPuestoIsNull() {
            addCriterion("V_PUESTO is null");
            return (Criteria) this;
        }

        public Criteria andVPuestoIsNotNull() {
            addCriterion("V_PUESTO is not null");
            return (Criteria) this;
        }

        public Criteria andVPuestoEqualTo(String value) {
            addCriterion("V_PUESTO =", value, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoNotEqualTo(String value) {
            addCriterion("V_PUESTO <>", value, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoGreaterThan(String value) {
            addCriterion("V_PUESTO >", value, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoGreaterThanOrEqualTo(String value) {
            addCriterion("V_PUESTO >=", value, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoLessThan(String value) {
            addCriterion("V_PUESTO <", value, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoLessThanOrEqualTo(String value) {
            addCriterion("V_PUESTO <=", value, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoLike(String value) {
            addCriterion("V_PUESTO like", value, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoNotLike(String value) {
            addCriterion("V_PUESTO not like", value, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoIn(List<String> values) {
            addCriterion("V_PUESTO in", values, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoNotIn(List<String> values) {
            addCriterion("V_PUESTO not in", values, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoBetween(String value1, String value2) {
            addCriterion("V_PUESTO between", value1, value2, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVPuestoNotBetween(String value1, String value2) {
            addCriterion("V_PUESTO not between", value1, value2, "vPuesto");
            return (Criteria) this;
        }

        public Criteria andVFuncionesIsNull() {
            addCriterion("V_FUNCIONES is null");
            return (Criteria) this;
        }

        public Criteria andVFuncionesIsNotNull() {
            addCriterion("V_FUNCIONES is not null");
            return (Criteria) this;
        }

        public Criteria andVFuncionesEqualTo(String value) {
            addCriterion("V_FUNCIONES =", value, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesNotEqualTo(String value) {
            addCriterion("V_FUNCIONES <>", value, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesGreaterThan(String value) {
            addCriterion("V_FUNCIONES >", value, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesGreaterThanOrEqualTo(String value) {
            addCriterion("V_FUNCIONES >=", value, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesLessThan(String value) {
            addCriterion("V_FUNCIONES <", value, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesLessThanOrEqualTo(String value) {
            addCriterion("V_FUNCIONES <=", value, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesLike(String value) {
            addCriterion("V_FUNCIONES like", value, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesNotLike(String value) {
            addCriterion("V_FUNCIONES not like", value, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesIn(List<String> values) {
            addCriterion("V_FUNCIONES in", values, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesNotIn(List<String> values) {
            addCriterion("V_FUNCIONES not in", values, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesBetween(String value1, String value2) {
            addCriterion("V_FUNCIONES between", value1, value2, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andVFuncionesNotBetween(String value1, String value2) {
            addCriterion("V_FUNCIONES not between", value1, value2, "vFunciones");
            return (Criteria) this;
        }

        public Criteria andDFeciniIsNull() {
            addCriterion("D_FECINI is null");
            return (Criteria) this;
        }

        public Criteria andDFeciniIsNotNull() {
            addCriterion("D_FECINI is not null");
            return (Criteria) this;
        }

        public Criteria andDFeciniEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECINI =", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECINI <>", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECINI >", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECINI >=", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniLessThan(Date value) {
            addCriterionForJDBCDate("D_FECINI <", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECINI <=", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECINI in", values, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECINI not in", values, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECINI between", value1, value2, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECINI not between", value1, value2, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFecfinIsNull() {
            addCriterion("D_FECFIN is null");
            return (Criteria) this;
        }

        public Criteria andDFecfinIsNotNull() {
            addCriterion("D_FECFIN is not null");
            return (Criteria) this;
        }

        public Criteria andDFecfinEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECFIN =", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECFIN <>", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECFIN >", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECFIN >=", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinLessThan(Date value) {
            addCriterionForJDBCDate("D_FECFIN <", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECFIN <=", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECFIN in", values, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECFIN not in", values, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECFIN between", value1, value2, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECFIN not between", value1, value2, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andNTiempanoIsNull() {
            addCriterion("N_TIEMPANO is null");
            return (Criteria) this;
        }

        public Criteria andNTiempanoIsNotNull() {
            addCriterion("N_TIEMPANO is not null");
            return (Criteria) this;
        }

        public Criteria andNTiempanoEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPANO =", value, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoNotEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPANO <>", value, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoGreaterThan(BigDecimal value) {
            addCriterion("N_TIEMPANO >", value, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPANO >=", value, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoLessThan(BigDecimal value) {
            addCriterion("N_TIEMPANO <", value, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPANO <=", value, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoIn(List<BigDecimal> values) {
            addCriterion("N_TIEMPANO in", values, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoNotIn(List<BigDecimal> values) {
            addCriterion("N_TIEMPANO not in", values, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_TIEMPANO between", value1, value2, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempanoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_TIEMPANO not between", value1, value2, "nTiempano");
            return (Criteria) this;
        }

        public Criteria andNTiempmesIsNull() {
            addCriterion("N_TIEMPMES is null");
            return (Criteria) this;
        }

        public Criteria andNTiempmesIsNotNull() {
            addCriterion("N_TIEMPMES is not null");
            return (Criteria) this;
        }

        public Criteria andNTiempmesEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPMES =", value, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesNotEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPMES <>", value, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesGreaterThan(BigDecimal value) {
            addCriterion("N_TIEMPMES >", value, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPMES >=", value, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesLessThan(BigDecimal value) {
            addCriterion("N_TIEMPMES <", value, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPMES <=", value, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesIn(List<BigDecimal> values) {
            addCriterion("N_TIEMPMES in", values, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesNotIn(List<BigDecimal> values) {
            addCriterion("N_TIEMPMES not in", values, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_TIEMPMES between", value1, value2, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempmesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_TIEMPMES not between", value1, value2, "nTiempmes");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaIsNull() {
            addCriterion("N_TIEMPDIA is null");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaIsNotNull() {
            addCriterion("N_TIEMPDIA is not null");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPDIA =", value, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaNotEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPDIA <>", value, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaGreaterThan(BigDecimal value) {
            addCriterion("N_TIEMPDIA >", value, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPDIA >=", value, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaLessThan(BigDecimal value) {
            addCriterion("N_TIEMPDIA <", value, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_TIEMPDIA <=", value, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaIn(List<BigDecimal> values) {
            addCriterion("N_TIEMPDIA in", values, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaNotIn(List<BigDecimal> values) {
            addCriterion("N_TIEMPDIA not in", values, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_TIEMPDIA between", value1, value2, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andNTiempdiaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_TIEMPDIA not between", value1, value2, "nTiempdia");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpIsNull() {
            addCriterion("V_FLGTIPEXP is null");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpIsNotNull() {
            addCriterion("V_FLGTIPEXP is not null");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpEqualTo(String value) {
            addCriterion("V_FLGTIPEXP =", value, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpNotEqualTo(String value) {
            addCriterion("V_FLGTIPEXP <>", value, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpGreaterThan(String value) {
            addCriterion("V_FLGTIPEXP >", value, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpGreaterThanOrEqualTo(String value) {
            addCriterion("V_FLGTIPEXP >=", value, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpLessThan(String value) {
            addCriterion("V_FLGTIPEXP <", value, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpLessThanOrEqualTo(String value) {
            addCriterion("V_FLGTIPEXP <=", value, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpLike(String value) {
            addCriterion("V_FLGTIPEXP like", value, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpNotLike(String value) {
            addCriterion("V_FLGTIPEXP not like", value, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpIn(List<String> values) {
            addCriterion("V_FLGTIPEXP in", values, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpNotIn(List<String> values) {
            addCriterion("V_FLGTIPEXP not in", values, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpBetween(String value1, String value2) {
            addCriterion("V_FLGTIPEXP between", value1, value2, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andVFlgtipexpNotBetween(String value1, String value2) {
            addCriterion("V_FLGTIPEXP not between", value1, value2, "vFlgtipexp");
            return (Criteria) this;
        }

        public Criteria andDFecregIsNull() {
            addCriterion("D_FECREG is null");
            return (Criteria) this;
        }

        public Criteria andDFecregIsNotNull() {
            addCriterion("D_FECREG is not null");
            return (Criteria) this;
        }

        public Criteria andDFecregEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG =", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG <>", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECREG >", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG >=", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregLessThan(Date value) {
            addCriterionForJDBCDate("D_FECREG <", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG <=", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECREG in", values, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECREG not in", values, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECREG between", value1, value2, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECREG not between", value1, value2, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andVHostregIsNull() {
            addCriterion("V_HOSTREG is null");
            return (Criteria) this;
        }

        public Criteria andVHostregIsNotNull() {
            addCriterion("V_HOSTREG is not null");
            return (Criteria) this;
        }

        public Criteria andVHostregEqualTo(String value) {
            addCriterion("V_HOSTREG =", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotEqualTo(String value) {
            addCriterion("V_HOSTREG <>", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregGreaterThan(String value) {
            addCriterion("V_HOSTREG >", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregGreaterThanOrEqualTo(String value) {
            addCriterion("V_HOSTREG >=", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLessThan(String value) {
            addCriterion("V_HOSTREG <", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLessThanOrEqualTo(String value) {
            addCriterion("V_HOSTREG <=", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLike(String value) {
            addCriterion("V_HOSTREG like", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotLike(String value) {
            addCriterion("V_HOSTREG not like", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregIn(List<String> values) {
            addCriterion("V_HOSTREG in", values, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotIn(List<String> values) {
            addCriterion("V_HOSTREG not in", values, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregBetween(String value1, String value2) {
            addCriterion("V_HOSTREG between", value1, value2, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotBetween(String value1, String value2) {
            addCriterion("V_HOSTREG not between", value1, value2, "vHostreg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 15 11:22:42 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHMVC_EXPERIENCIA
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}