package pe.gob.sunafil.postulacioncas.persistence.model;

import java.math.BigDecimal;

public class RhtbcTipcapacitac {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBC_TIPCAPACITAC.N_CORTIPCAP
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    private BigDecimal nCortipcap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBC_TIPCAPACITAC.V_DESTIPCAP
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    private String vDestipcap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RRHHSYS.RHTBC_TIPCAPACITAC.V_FLGACT
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    private String vFlgact;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBC_TIPCAPACITAC.N_CORTIPCAP
     *
     * @return the value of RRHHSYS.RHTBC_TIPCAPACITAC.N_CORTIPCAP
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public BigDecimal getnCortipcap() {
        return nCortipcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBC_TIPCAPACITAC.N_CORTIPCAP
     *
     * @param nCortipcap the value for RRHHSYS.RHTBC_TIPCAPACITAC.N_CORTIPCAP
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public void setnCortipcap(BigDecimal nCortipcap) {
        this.nCortipcap = nCortipcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBC_TIPCAPACITAC.V_DESTIPCAP
     *
     * @return the value of RRHHSYS.RHTBC_TIPCAPACITAC.V_DESTIPCAP
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public String getvDestipcap() {
        return vDestipcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBC_TIPCAPACITAC.V_DESTIPCAP
     *
     * @param vDestipcap the value for RRHHSYS.RHTBC_TIPCAPACITAC.V_DESTIPCAP
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public void setvDestipcap(String vDestipcap) {
        this.vDestipcap = vDestipcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RRHHSYS.RHTBC_TIPCAPACITAC.V_FLGACT
     *
     * @return the value of RRHHSYS.RHTBC_TIPCAPACITAC.V_FLGACT
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public String getvFlgact() {
        return vFlgact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RRHHSYS.RHTBC_TIPCAPACITAC.V_FLGACT
     *
     * @param vFlgact the value for RRHHSYS.RHTBC_TIPCAPACITAC.V_FLGACT
     *
     * @mbggenerated Wed Mar 15 11:22:42 COT 2017
     */
    public void setvFlgact(String vFlgact) {
        this.vFlgact = vFlgact;
    }
}