package pe.gob.sunafil.postulacioncas.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.postulacioncas.persistence.model.RhtbcConvocatoria;
import pe.gob.sunafil.postulacioncas.persistence.model.RhtbcConvocatoriaExample;

public interface RhtbcConvocatoriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int countByExample(RhtbcConvocatoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int deleteByExample(RhtbcConvocatoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int deleteByPrimaryKey(BigDecimal nCorconv);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int insert(RhtbcConvocatoria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int insertSelective(RhtbcConvocatoria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    List<RhtbcConvocatoria> selectByExample(RhtbcConvocatoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    RhtbcConvocatoria selectByPrimaryKey(BigDecimal nCorconv);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int updateByExampleSelective(@Param("record") RhtbcConvocatoria record, @Param("example") RhtbcConvocatoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int updateByExample(@Param("record") RhtbcConvocatoria record, @Param("example") RhtbcConvocatoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int updateByPrimaryKeySelective(RhtbcConvocatoria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_CONVOCATORIA
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    int updateByPrimaryKey(RhtbcConvocatoria record);
}