package pe.gob.sunafil.postulacioncas.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.postulacioncas.persistence.model.SitbPersona;
import pe.gob.sunafil.postulacioncas.persistence.model.SitbPersonaExample;
import pe.gob.sunafil.postulacioncas.persistence.model.SitbPersonaKey;

public interface SitbPersonaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int countByExample(SitbPersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int deleteByExample(SitbPersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int deleteByPrimaryKey(SitbPersonaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int insert(SitbPersona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int insertSelective(SitbPersona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    List<SitbPersona> selectByExample(SitbPersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    SitbPersona selectByPrimaryKey(SitbPersonaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int updateByExampleSelective(@Param("record") SitbPersona record, @Param("example") SitbPersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int updateByExample(@Param("record") SitbPersona record, @Param("example") SitbPersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int updateByPrimaryKeySelective(SitbPersona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIMINTRA1.SITB_PERSONA
     *
     * @mbggenerated Mon Mar 13 15:50:20 COT 2017
     */
    int updateByPrimaryKey(SitbPersona record);
}