package pe.gob.sunafil.postulacioncas.persistence.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import pe.gob.sunafil.postulacioncas.persistence.model.RhtbcHojadevidaExample.Criteria;

public class RhmvcHvxformacionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public RhmvcHvxformacionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andNCorhvforIsNull() {
            addCriterion("N_CORHVFOR is null");
            return (Criteria) this;
        }

        public Criteria andNCorhvforIsNotNull() {
            addCriterion("N_CORHVFOR is not null");
            return (Criteria) this;
        }

        public Criteria andNCorhvforEqualTo(BigDecimal value) {
            addCriterion("N_CORHVFOR =", value, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforNotEqualTo(BigDecimal value) {
            addCriterion("N_CORHVFOR <>", value, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforGreaterThan(BigDecimal value) {
            addCriterion("N_CORHVFOR >", value, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORHVFOR >=", value, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforLessThan(BigDecimal value) {
            addCriterion("N_CORHVFOR <", value, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORHVFOR <=", value, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforIn(List<BigDecimal> values) {
            addCriterion("N_CORHVFOR in", values, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforNotIn(List<BigDecimal> values) {
            addCriterion("N_CORHVFOR not in", values, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORHVFOR between", value1, value2, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhvforNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORHVFOR not between", value1, value2, "nCorhvfor");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidIsNull() {
            addCriterion("N_CORHOJVID is null");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidIsNotNull() {
            addCriterion("N_CORHOJVID is not null");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidEqualTo(BigDecimal value) {
            addCriterion("N_CORHOJVID =", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidNotEqualTo(BigDecimal value) {
            addCriterion("N_CORHOJVID <>", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidGreaterThan(BigDecimal value) {
            addCriterion("N_CORHOJVID >", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORHOJVID >=", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidLessThan(BigDecimal value) {
            addCriterion("N_CORHOJVID <", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORHOJVID <=", value, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidIn(List<BigDecimal> values) {
            addCriterion("N_CORHOJVID in", values, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidNotIn(List<BigDecimal> values) {
            addCriterion("N_CORHOJVID not in", values, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORHOJVID between", value1, value2, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCorhojvidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORHOJVID not between", value1, value2, "nCorhojvid");
            return (Criteria) this;
        }

        public Criteria andNCodforIsNull() {
            addCriterion("N_CODFOR is null");
            return (Criteria) this;
        }

        public Criteria andNCodforIsNotNull() {
            addCriterion("N_CODFOR is not null");
            return (Criteria) this;
        }

        public Criteria andNCodforEqualTo(BigDecimal value) {
            addCriterion("N_CODFOR =", value, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforNotEqualTo(BigDecimal value) {
            addCriterion("N_CODFOR <>", value, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforGreaterThan(BigDecimal value) {
            addCriterion("N_CODFOR >", value, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CODFOR >=", value, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforLessThan(BigDecimal value) {
            addCriterion("N_CODFOR <", value, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CODFOR <=", value, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforIn(List<BigDecimal> values) {
            addCriterion("N_CODFOR in", values, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforNotIn(List<BigDecimal> values) {
            addCriterion("N_CODFOR not in", values, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CODFOR between", value1, value2, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCodforNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CODFOR not between", value1, value2, "nCodfor");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaIsNull() {
            addCriterion("N_CORGRAACA is null");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaIsNotNull() {
            addCriterion("N_CORGRAACA is not null");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaEqualTo(BigDecimal value) {
            addCriterion("N_CORGRAACA =", value, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaNotEqualTo(BigDecimal value) {
            addCriterion("N_CORGRAACA <>", value, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaGreaterThan(BigDecimal value) {
            addCriterion("N_CORGRAACA >", value, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORGRAACA >=", value, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaLessThan(BigDecimal value) {
            addCriterion("N_CORGRAACA <", value, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CORGRAACA <=", value, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaIn(List<BigDecimal> values) {
            addCriterion("N_CORGRAACA in", values, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaNotIn(List<BigDecimal> values) {
            addCriterion("N_CORGRAACA not in", values, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORGRAACA between", value1, value2, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andNCorgraacaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CORGRAACA not between", value1, value2, "nCorgraaca");
            return (Criteria) this;
        }

        public Criteria andVCentroestIsNull() {
            addCriterion("V_CENTROEST is null");
            return (Criteria) this;
        }

        public Criteria andVCentroestIsNotNull() {
            addCriterion("V_CENTROEST is not null");
            return (Criteria) this;
        }

        public Criteria andVCentroestEqualTo(String value) {
            addCriterion("V_CENTROEST =", value, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestNotEqualTo(String value) {
            addCriterion("V_CENTROEST <>", value, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestGreaterThan(String value) {
            addCriterion("V_CENTROEST >", value, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestGreaterThanOrEqualTo(String value) {
            addCriterion("V_CENTROEST >=", value, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestLessThan(String value) {
            addCriterion("V_CENTROEST <", value, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestLessThanOrEqualTo(String value) {
            addCriterion("V_CENTROEST <=", value, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestLike(String value) {
            addCriterion("V_CENTROEST like", value, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestNotLike(String value) {
            addCriterion("V_CENTROEST not like", value, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestIn(List<String> values) {
            addCriterion("V_CENTROEST in", values, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestNotIn(List<String> values) {
            addCriterion("V_CENTROEST not in", values, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestBetween(String value1, String value2) {
            addCriterion("V_CENTROEST between", value1, value2, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVCentroestNotBetween(String value1, String value2) {
            addCriterion("V_CENTROEST not between", value1, value2, "vCentroest");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadIsNull() {
            addCriterion("V_ESPECIALIDAD is null");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadIsNotNull() {
            addCriterion("V_ESPECIALIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadEqualTo(String value) {
            addCriterion("V_ESPECIALIDAD =", value, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadNotEqualTo(String value) {
            addCriterion("V_ESPECIALIDAD <>", value, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadGreaterThan(String value) {
            addCriterion("V_ESPECIALIDAD >", value, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadGreaterThanOrEqualTo(String value) {
            addCriterion("V_ESPECIALIDAD >=", value, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadLessThan(String value) {
            addCriterion("V_ESPECIALIDAD <", value, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadLessThanOrEqualTo(String value) {
            addCriterion("V_ESPECIALIDAD <=", value, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadLike(String value) {
            addCriterion("V_ESPECIALIDAD like", value, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadNotLike(String value) {
            addCriterion("V_ESPECIALIDAD not like", value, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadIn(List<String> values) {
            addCriterion("V_ESPECIALIDAD in", values, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadNotIn(List<String> values) {
            addCriterion("V_ESPECIALIDAD not in", values, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadBetween(String value1, String value2) {
            addCriterion("V_ESPECIALIDAD between", value1, value2, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andVEspecialidadNotBetween(String value1, String value2) {
            addCriterion("V_ESPECIALIDAD not between", value1, value2, "vEspecialidad");
            return (Criteria) this;
        }

        public Criteria andDFeciniIsNull() {
            addCriterion("D_FECINI is null");
            return (Criteria) this;
        }

        public Criteria andDFeciniIsNotNull() {
            addCriterion("D_FECINI is not null");
            return (Criteria) this;
        }

        public Criteria andDFeciniEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECINI =", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECINI <>", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECINI >", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECINI >=", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniLessThan(Date value) {
            addCriterionForJDBCDate("D_FECINI <", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECINI <=", value, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECINI in", values, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECINI not in", values, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECINI between", value1, value2, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFeciniNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECINI not between", value1, value2, "dFecini");
            return (Criteria) this;
        }

        public Criteria andDFecfinIsNull() {
            addCriterion("D_FECFIN is null");
            return (Criteria) this;
        }

        public Criteria andDFecfinIsNotNull() {
            addCriterion("D_FECFIN is not null");
            return (Criteria) this;
        }

        public Criteria andDFecfinEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECFIN =", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECFIN <>", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECFIN >", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECFIN >=", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinLessThan(Date value) {
            addCriterionForJDBCDate("D_FECFIN <", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECFIN <=", value, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECFIN in", values, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECFIN not in", values, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECFIN between", value1, value2, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecfinNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECFIN not between", value1, value2, "dFecfin");
            return (Criteria) this;
        }

        public Criteria andDFecextdipIsNull() {
            addCriterion("D_FECEXTDIP is null");
            return (Criteria) this;
        }

        public Criteria andDFecextdipIsNotNull() {
            addCriterion("D_FECEXTDIP is not null");
            return (Criteria) this;
        }

        public Criteria andDFecextdipEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECEXTDIP =", value, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECEXTDIP <>", value, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECEXTDIP >", value, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECEXTDIP >=", value, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipLessThan(Date value) {
            addCriterionForJDBCDate("D_FECEXTDIP <", value, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECEXTDIP <=", value, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECEXTDIP in", values, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECEXTDIP not in", values, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECEXTDIP between", value1, value2, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andDFecextdipNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECEXTDIP not between", value1, value2, "dFecextdip");
            return (Criteria) this;
        }

        public Criteria andVCiudadIsNull() {
            addCriterion("V_CIUDAD is null");
            return (Criteria) this;
        }

        public Criteria andVCiudadIsNotNull() {
            addCriterion("V_CIUDAD is not null");
            return (Criteria) this;
        }

        public Criteria andVCiudadEqualTo(String value) {
            addCriterion("V_CIUDAD =", value, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadNotEqualTo(String value) {
            addCriterion("V_CIUDAD <>", value, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadGreaterThan(String value) {
            addCriterion("V_CIUDAD >", value, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadGreaterThanOrEqualTo(String value) {
            addCriterion("V_CIUDAD >=", value, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadLessThan(String value) {
            addCriterion("V_CIUDAD <", value, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadLessThanOrEqualTo(String value) {
            addCriterion("V_CIUDAD <=", value, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadLike(String value) {
            addCriterion("V_CIUDAD like", value, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadNotLike(String value) {
            addCriterion("V_CIUDAD not like", value, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadIn(List<String> values) {
            addCriterion("V_CIUDAD in", values, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadNotIn(List<String> values) {
            addCriterion("V_CIUDAD not in", values, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadBetween(String value1, String value2) {
            addCriterion("V_CIUDAD between", value1, value2, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCiudadNotBetween(String value1, String value2) {
            addCriterion("V_CIUDAD not between", value1, value2, "vCiudad");
            return (Criteria) this;
        }

        public Criteria andVCodpaisIsNull() {
            addCriterion("V_CODPAIS is null");
            return (Criteria) this;
        }

        public Criteria andVCodpaisIsNotNull() {
            addCriterion("V_CODPAIS is not null");
            return (Criteria) this;
        }

        public Criteria andVCodpaisEqualTo(String value) {
            addCriterion("V_CODPAIS =", value, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisNotEqualTo(String value) {
            addCriterion("V_CODPAIS <>", value, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisGreaterThan(String value) {
            addCriterion("V_CODPAIS >", value, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisGreaterThanOrEqualTo(String value) {
            addCriterion("V_CODPAIS >=", value, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisLessThan(String value) {
            addCriterion("V_CODPAIS <", value, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisLessThanOrEqualTo(String value) {
            addCriterion("V_CODPAIS <=", value, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisLike(String value) {
            addCriterion("V_CODPAIS like", value, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisNotLike(String value) {
            addCriterion("V_CODPAIS not like", value, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisIn(List<String> values) {
            addCriterion("V_CODPAIS in", values, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisNotIn(List<String> values) {
            addCriterion("V_CODPAIS not in", values, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisBetween(String value1, String value2) {
            addCriterion("V_CODPAIS between", value1, value2, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andVCodpaisNotBetween(String value1, String value2) {
            addCriterion("V_CODPAIS not between", value1, value2, "vCodpais");
            return (Criteria) this;
        }

        public Criteria andDFecregIsNull() {
            addCriterion("D_FECREG is null");
            return (Criteria) this;
        }

        public Criteria andDFecregIsNotNull() {
            addCriterion("D_FECREG is not null");
            return (Criteria) this;
        }

        public Criteria andDFecregEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG =", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG <>", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregGreaterThan(Date value) {
            addCriterionForJDBCDate("D_FECREG >", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG >=", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregLessThan(Date value) {
            addCriterionForJDBCDate("D_FECREG <", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("D_FECREG <=", value, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECREG in", values, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotIn(List<Date> values) {
            addCriterionForJDBCDate("D_FECREG not in", values, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECREG between", value1, value2, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andDFecregNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("D_FECREG not between", value1, value2, "dFecreg");
            return (Criteria) this;
        }

        public Criteria andVHostregIsNull() {
            addCriterion("V_HOSTREG is null");
            return (Criteria) this;
        }

        public Criteria andVHostregIsNotNull() {
            addCriterion("V_HOSTREG is not null");
            return (Criteria) this;
        }

        public Criteria andVHostregEqualTo(String value) {
            addCriterion("V_HOSTREG =", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotEqualTo(String value) {
            addCriterion("V_HOSTREG <>", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregGreaterThan(String value) {
            addCriterion("V_HOSTREG >", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregGreaterThanOrEqualTo(String value) {
            addCriterion("V_HOSTREG >=", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLessThan(String value) {
            addCriterion("V_HOSTREG <", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLessThanOrEqualTo(String value) {
            addCriterion("V_HOSTREG <=", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregLike(String value) {
            addCriterion("V_HOSTREG like", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotLike(String value) {
            addCriterion("V_HOSTREG not like", value, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregIn(List<String> values) {
            addCriterion("V_HOSTREG in", values, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotIn(List<String> values) {
            addCriterion("V_HOSTREG not in", values, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregBetween(String value1, String value2) {
            addCriterion("V_HOSTREG between", value1, value2, "vHostreg");
            return (Criteria) this;
        }

        public Criteria andVHostregNotBetween(String value1, String value2) {
            addCriterion("V_HOSTREG not between", value1, value2, "vHostreg");
            return (Criteria) this;
        }
        
        public Criteria andCorrelativoActual() {
      	  StringBuffer sb = new StringBuffer("N_CORHVFOR in (select max(N_CORHVFOR) from RRHHSYS.RHMVC_HVXFORMACION)");    	  
      	  addCriterion(sb.toString());
      	  return (Criteria) this;
      	}
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 09 14:36:47 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RRHHSYS.RHMVC_HVXFORMACION
     *
     * @mbggenerated Thu Mar 09 14:36:47 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}