package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhmvcPerturno;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhmvcPerturnoExample;

public interface RhmvcPerturnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int countByExample(RhmvcPerturnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int deleteByExample(RhmvcPerturnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int deleteByPrimaryKey(Short nCodperturno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int insert(RhmvcPerturno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int insertSelective(RhmvcPerturno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    List<RhmvcPerturno> selectByExample(RhmvcPerturnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    RhmvcPerturno selectByPrimaryKey(Short nCodperturno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int updateByExampleSelective(@Param("record") RhmvcPerturno record, @Param("example") RhmvcPerturnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int updateByExample(@Param("record") RhmvcPerturno record, @Param("example") RhmvcPerturnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int updateByPrimaryKeySelective(RhmvcPerturno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_PERTURNO
     *
     * @mbggenerated Wed Oct 05 11:06:41 COT 2016
     */
    int updateByPrimaryKey(RhmvcPerturno record);
}