package pe.gob.sunafil.tramiteext.persistence.model;

public class TdtbdReqtupa extends TdtbdReqtupaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBD_REQTUPA.N_FLGACTIVO
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    private Short nFlgactivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBD_REQTUPA.V_DESREQ
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    private String vDesreq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBD_REQTUPA.N_FLGACTIVO
     *
     * @return the value of TRAMITE.TDTBD_REQTUPA.N_FLGACTIVO
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    public Short getnFlgactivo() {
        return nFlgactivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBD_REQTUPA.N_FLGACTIVO
     *
     * @param nFlgactivo the value for TRAMITE.TDTBD_REQTUPA.N_FLGACTIVO
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    public void setnFlgactivo(Short nFlgactivo) {
        this.nFlgactivo = nFlgactivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBD_REQTUPA.V_DESREQ
     *
     * @return the value of TRAMITE.TDTBD_REQTUPA.V_DESREQ
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    public String getvDesreq() {
        return vDesreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBD_REQTUPA.V_DESREQ
     *
     * @param vDesreq the value for TRAMITE.TDTBD_REQTUPA.V_DESREQ
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    public void setvDesreq(String vDesreq) {
        this.vDesreq = vDesreq;
    }
}