package pe.gob.sunafil.tramiteext.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.tramiteext.persistence.model.TdbcDependenciasiit;
import pe.gob.sunafil.tramiteext.persistence.model.TdbcDependenciasiitExample;
import pe.gob.sunafil.tramiteext.persistence.model.TdbcDependenciasiitKey;

public interface TdbcDependenciasiitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int countByExample(TdbcDependenciasiitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int deleteByExample(TdbcDependenciasiitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int deleteByPrimaryKey(TdbcDependenciasiitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int insert(TdbcDependenciasiit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int insertSelective(TdbcDependenciasiit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    List<TdbcDependenciasiit> selectByExample(TdbcDependenciasiitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    TdbcDependenciasiit selectByPrimaryKey(TdbcDependenciasiitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") TdbcDependenciasiit record, @Param("example") TdbcDependenciasiitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int updateByExample(@Param("record") TdbcDependenciasiit record, @Param("example") TdbcDependenciasiitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int updateByPrimaryKeySelective(TdbcDependenciasiit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDBC_DEPENDENCIASIIT
     *
     * @mbggenerated Tue Mar 14 12:53:03 COT 2017
     */
    int updateByPrimaryKey(TdbcDependenciasiit record);
}