package pe.gob.sunafil.tramiteext.siit.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.tramiteext.siit.persistence.model.VstSiitToTramite;
import pe.gob.sunafil.tramiteext.siit.persistence.model.VstSiitToTramiteExample;

public interface VstSiitToTramiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_SIIT_TO_TRAMITE
     *
     * @mbggenerated Fri Dec 16 15:23:35 COT 2016
     */
    int countByExample(VstSiitToTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_SIIT_TO_TRAMITE
     *
     * @mbggenerated Fri Dec 16 15:23:35 COT 2016
     */
    int deleteByExample(VstSiitToTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_SIIT_TO_TRAMITE
     *
     * @mbggenerated Fri Dec 16 15:23:35 COT 2016
     */
    int insert(VstSiitToTramite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_SIIT_TO_TRAMITE
     *
     * @mbggenerated Fri Dec 16 15:23:35 COT 2016
     */
    int insertSelective(VstSiitToTramite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_SIIT_TO_TRAMITE
     *
     * @mbggenerated Fri Dec 16 15:23:35 COT 2016
     */
    List<VstSiitToTramite> selectByExample(VstSiitToTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_SIIT_TO_TRAMITE
     *
     * @mbggenerated Fri Dec 16 15:23:35 COT 2016
     */
    int updateByExampleSelective(@Param("record") VstSiitToTramite record, @Param("example") VstSiitToTramiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIIT.VST_SIIT_TO_TRAMITE
     *
     * @mbggenerated Fri Dec 16 15:23:35 COT 2016
     */
    int updateByExample(@Param("record") VstSiitToTramite record, @Param("example") VstSiitToTramiteExample example);
}