package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhtbcErrcarmas;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhtbcErrcarmasExample;

public interface RhtbcErrcarmasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int countByExample(RhtbcErrcarmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int deleteByExample(RhtbcErrcarmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int deleteByPrimaryKey(BigDecimal nCoderror);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int insert(RhtbcErrcarmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int insertSelective(RhtbcErrcarmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    List<RhtbcErrcarmas> selectByExample(RhtbcErrcarmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    RhtbcErrcarmas selectByPrimaryKey(BigDecimal nCoderror);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int updateByExampleSelective(@Param("record") RhtbcErrcarmas record, @Param("example") RhtbcErrcarmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int updateByExample(@Param("record") RhtbcErrcarmas record, @Param("example") RhtbcErrcarmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int updateByPrimaryKeySelective(RhtbcErrcarmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHTBC_ERRCARMAS
     *
     * @mbggenerated Wed Dec 21 14:49:55 COT 2016
     */
    int updateByPrimaryKey(RhtbcErrcarmas record);
}