package pe.gob.sunafil.denunciavirtual.siit.persistence.model;

import java.math.BigDecimal;
import java.util.Date;

public class SitbEmpleador {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODSEC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodsec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODCIIU
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodciiu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODDEP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCoddep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODPRO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODDIS
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCoddis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTVIA
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodtvia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_RAZSOC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vRazsoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_NOMCOM
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vNomcom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.D_FECINIACT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private Date dFeciniact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_DIREMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vDiremp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_URBEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vUrbemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMPISO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vNumpiso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vNumemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_TELEMP1
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vTelemp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_TELEMP2
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vTelemp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_FAXEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vFaxemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_KIMEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vKimemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_MANEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vManemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_LOTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vLotemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_INTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vIntemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vFlgemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODUSUREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodusureg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.D_FECREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private Date dFecreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_HOSTREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vHostreg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODUSUMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodusumod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.D_FECMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private Date dFecmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_HOSTMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vHostmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_TIPEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vTipemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODCIIURES
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodciiures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_DIRREF
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vDirref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.N_FLGACTIVO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private Short nFlgactivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODZONA
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodzona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodtemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMRUC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vNumruc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGSUNAT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vFlgsunat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.N_CORREL
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private BigDecimal nCorrel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_SECTOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vSector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_GRUPO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vGrupo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_EMAIL
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGSIIT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vFlgsiit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTIPCON
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodtipcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_CODESTCON
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vCodestcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.N_ESTMYPE
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private BigDecimal nEstmype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGACRED
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String vFlgacred;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_DEPORI
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String sunatDepori;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_OPERAC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String sunatOperac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_CORNOV
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String sunatCornov;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_NUMPRO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    private String sunatNumpro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodemp() {
        return vCodemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODEMP
     *
     * @param vCodemp the value for SIMINTRA1.SITB_EMPLEADOR.V_CODEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodemp(String vCodemp) {
        this.vCodemp = vCodemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODSEC
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODSEC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodsec() {
        return vCodsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODSEC
     *
     * @param vCodsec the value for SIMINTRA1.SITB_EMPLEADOR.V_CODSEC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodsec(String vCodsec) {
        this.vCodsec = vCodsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODCIIU
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODCIIU
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodciiu() {
        return vCodciiu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODCIIU
     *
     * @param vCodciiu the value for SIMINTRA1.SITB_EMPLEADOR.V_CODCIIU
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodciiu(String vCodciiu) {
        this.vCodciiu = vCodciiu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODDEP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODDEP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCoddep() {
        return vCoddep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODDEP
     *
     * @param vCoddep the value for SIMINTRA1.SITB_EMPLEADOR.V_CODDEP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCoddep(String vCoddep) {
        this.vCoddep = vCoddep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODPRO
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODPRO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodpro() {
        return vCodpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODPRO
     *
     * @param vCodpro the value for SIMINTRA1.SITB_EMPLEADOR.V_CODPRO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodpro(String vCodpro) {
        this.vCodpro = vCodpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODDIS
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODDIS
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCoddis() {
        return vCoddis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODDIS
     *
     * @param vCoddis the value for SIMINTRA1.SITB_EMPLEADOR.V_CODDIS
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCoddis(String vCoddis) {
        this.vCoddis = vCoddis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTVIA
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODTVIA
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodtvia() {
        return vCodtvia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTVIA
     *
     * @param vCodtvia the value for SIMINTRA1.SITB_EMPLEADOR.V_CODTVIA
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodtvia(String vCodtvia) {
        this.vCodtvia = vCodtvia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_RAZSOC
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_RAZSOC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvRazsoc() {
        return vRazsoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_RAZSOC
     *
     * @param vRazsoc the value for SIMINTRA1.SITB_EMPLEADOR.V_RAZSOC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvRazsoc(String vRazsoc) {
        this.vRazsoc = vRazsoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_NOMCOM
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_NOMCOM
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvNomcom() {
        return vNomcom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_NOMCOM
     *
     * @param vNomcom the value for SIMINTRA1.SITB_EMPLEADOR.V_NOMCOM
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvNomcom(String vNomcom) {
        this.vNomcom = vNomcom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.D_FECINIACT
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.D_FECINIACT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public Date getdFeciniact() {
        return dFeciniact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.D_FECINIACT
     *
     * @param dFeciniact the value for SIMINTRA1.SITB_EMPLEADOR.D_FECINIACT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setdFeciniact(Date dFeciniact) {
        this.dFeciniact = dFeciniact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_DIREMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_DIREMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvDiremp() {
        return vDiremp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_DIREMP
     *
     * @param vDiremp the value for SIMINTRA1.SITB_EMPLEADOR.V_DIREMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvDiremp(String vDiremp) {
        this.vDiremp = vDiremp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_URBEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_URBEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvUrbemp() {
        return vUrbemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_URBEMP
     *
     * @param vUrbemp the value for SIMINTRA1.SITB_EMPLEADOR.V_URBEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvUrbemp(String vUrbemp) {
        this.vUrbemp = vUrbemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMPISO
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_NUMPISO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvNumpiso() {
        return vNumpiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMPISO
     *
     * @param vNumpiso the value for SIMINTRA1.SITB_EMPLEADOR.V_NUMPISO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvNumpiso(String vNumpiso) {
        this.vNumpiso = vNumpiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_NUMEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvNumemp() {
        return vNumemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMEMP
     *
     * @param vNumemp the value for SIMINTRA1.SITB_EMPLEADOR.V_NUMEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvNumemp(String vNumemp) {
        this.vNumemp = vNumemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_TELEMP1
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_TELEMP1
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvTelemp1() {
        return vTelemp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_TELEMP1
     *
     * @param vTelemp1 the value for SIMINTRA1.SITB_EMPLEADOR.V_TELEMP1
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvTelemp1(String vTelemp1) {
        this.vTelemp1 = vTelemp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_TELEMP2
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_TELEMP2
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvTelemp2() {
        return vTelemp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_TELEMP2
     *
     * @param vTelemp2 the value for SIMINTRA1.SITB_EMPLEADOR.V_TELEMP2
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvTelemp2(String vTelemp2) {
        this.vTelemp2 = vTelemp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FAXEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_FAXEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvFaxemp() {
        return vFaxemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FAXEMP
     *
     * @param vFaxemp the value for SIMINTRA1.SITB_EMPLEADOR.V_FAXEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvFaxemp(String vFaxemp) {
        this.vFaxemp = vFaxemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_KIMEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_KIMEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvKimemp() {
        return vKimemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_KIMEMP
     *
     * @param vKimemp the value for SIMINTRA1.SITB_EMPLEADOR.V_KIMEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvKimemp(String vKimemp) {
        this.vKimemp = vKimemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_MANEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_MANEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvManemp() {
        return vManemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_MANEMP
     *
     * @param vManemp the value for SIMINTRA1.SITB_EMPLEADOR.V_MANEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvManemp(String vManemp) {
        this.vManemp = vManemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_LOTEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_LOTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvLotemp() {
        return vLotemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_LOTEMP
     *
     * @param vLotemp the value for SIMINTRA1.SITB_EMPLEADOR.V_LOTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvLotemp(String vLotemp) {
        this.vLotemp = vLotemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_INTEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_INTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvIntemp() {
        return vIntemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_INTEMP
     *
     * @param vIntemp the value for SIMINTRA1.SITB_EMPLEADOR.V_INTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvIntemp(String vIntemp) {
        this.vIntemp = vIntemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_FLGEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvFlgemp() {
        return vFlgemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGEMP
     *
     * @param vFlgemp the value for SIMINTRA1.SITB_EMPLEADOR.V_FLGEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvFlgemp(String vFlgemp) {
        this.vFlgemp = vFlgemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODUSUREG
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODUSUREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodusureg() {
        return vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODUSUREG
     *
     * @param vCodusureg the value for SIMINTRA1.SITB_EMPLEADOR.V_CODUSUREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodusureg(String vCodusureg) {
        this.vCodusureg = vCodusureg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.D_FECREG
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.D_FECREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public Date getdFecreg() {
        return dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.D_FECREG
     *
     * @param dFecreg the value for SIMINTRA1.SITB_EMPLEADOR.D_FECREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setdFecreg(Date dFecreg) {
        this.dFecreg = dFecreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_HOSTREG
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_HOSTREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvHostreg() {
        return vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_HOSTREG
     *
     * @param vHostreg the value for SIMINTRA1.SITB_EMPLEADOR.V_HOSTREG
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvHostreg(String vHostreg) {
        this.vHostreg = vHostreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODUSUMOD
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODUSUMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodusumod() {
        return vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODUSUMOD
     *
     * @param vCodusumod the value for SIMINTRA1.SITB_EMPLEADOR.V_CODUSUMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodusumod(String vCodusumod) {
        this.vCodusumod = vCodusumod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.D_FECMOD
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.D_FECMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public Date getdFecmod() {
        return dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.D_FECMOD
     *
     * @param dFecmod the value for SIMINTRA1.SITB_EMPLEADOR.D_FECMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setdFecmod(Date dFecmod) {
        this.dFecmod = dFecmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_HOSTMOD
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_HOSTMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvHostmod() {
        return vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_HOSTMOD
     *
     * @param vHostmod the value for SIMINTRA1.SITB_EMPLEADOR.V_HOSTMOD
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvHostmod(String vHostmod) {
        this.vHostmod = vHostmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_TIPEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_TIPEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvTipemp() {
        return vTipemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_TIPEMP
     *
     * @param vTipemp the value for SIMINTRA1.SITB_EMPLEADOR.V_TIPEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvTipemp(String vTipemp) {
        this.vTipemp = vTipemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODCIIURES
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODCIIURES
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodciiures() {
        return vCodciiures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODCIIURES
     *
     * @param vCodciiures the value for SIMINTRA1.SITB_EMPLEADOR.V_CODCIIURES
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodciiures(String vCodciiures) {
        this.vCodciiures = vCodciiures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_DIRREF
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_DIRREF
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvDirref() {
        return vDirref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_DIRREF
     *
     * @param vDirref the value for SIMINTRA1.SITB_EMPLEADOR.V_DIRREF
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvDirref(String vDirref) {
        this.vDirref = vDirref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.N_FLGACTIVO
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.N_FLGACTIVO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public Short getnFlgactivo() {
        return nFlgactivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.N_FLGACTIVO
     *
     * @param nFlgactivo the value for SIMINTRA1.SITB_EMPLEADOR.N_FLGACTIVO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setnFlgactivo(Short nFlgactivo) {
        this.nFlgactivo = nFlgactivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODZONA
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODZONA
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodzona() {
        return vCodzona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODZONA
     *
     * @param vCodzona the value for SIMINTRA1.SITB_EMPLEADOR.V_CODZONA
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodzona(String vCodzona) {
        this.vCodzona = vCodzona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTEMP
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodtemp() {
        return vCodtemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTEMP
     *
     * @param vCodtemp the value for SIMINTRA1.SITB_EMPLEADOR.V_CODTEMP
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodtemp(String vCodtemp) {
        this.vCodtemp = vCodtemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMRUC
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_NUMRUC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvNumruc() {
        return vNumruc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_NUMRUC
     *
     * @param vNumruc the value for SIMINTRA1.SITB_EMPLEADOR.V_NUMRUC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvNumruc(String vNumruc) {
        this.vNumruc = vNumruc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGSUNAT
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_FLGSUNAT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvFlgsunat() {
        return vFlgsunat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGSUNAT
     *
     * @param vFlgsunat the value for SIMINTRA1.SITB_EMPLEADOR.V_FLGSUNAT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvFlgsunat(String vFlgsunat) {
        this.vFlgsunat = vFlgsunat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.N_CORREL
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.N_CORREL
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public BigDecimal getnCorrel() {
        return nCorrel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.N_CORREL
     *
     * @param nCorrel the value for SIMINTRA1.SITB_EMPLEADOR.N_CORREL
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setnCorrel(BigDecimal nCorrel) {
        this.nCorrel = nCorrel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_SECTOR
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_SECTOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvSector() {
        return vSector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_SECTOR
     *
     * @param vSector the value for SIMINTRA1.SITB_EMPLEADOR.V_SECTOR
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvSector(String vSector) {
        this.vSector = vSector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_GRUPO
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_GRUPO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvGrupo() {
        return vGrupo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_GRUPO
     *
     * @param vGrupo the value for SIMINTRA1.SITB_EMPLEADOR.V_GRUPO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvGrupo(String vGrupo) {
        this.vGrupo = vGrupo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_EMAIL
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_EMAIL
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvEmail() {
        return vEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_EMAIL
     *
     * @param vEmail the value for SIMINTRA1.SITB_EMPLEADOR.V_EMAIL
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvEmail(String vEmail) {
        this.vEmail = vEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGSIIT
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_FLGSIIT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvFlgsiit() {
        return vFlgsiit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGSIIT
     *
     * @param vFlgsiit the value for SIMINTRA1.SITB_EMPLEADOR.V_FLGSIIT
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvFlgsiit(String vFlgsiit) {
        this.vFlgsiit = vFlgsiit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTIPCON
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODTIPCON
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodtipcon() {
        return vCodtipcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODTIPCON
     *
     * @param vCodtipcon the value for SIMINTRA1.SITB_EMPLEADOR.V_CODTIPCON
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodtipcon(String vCodtipcon) {
        this.vCodtipcon = vCodtipcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODESTCON
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_CODESTCON
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvCodestcon() {
        return vCodestcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_CODESTCON
     *
     * @param vCodestcon the value for SIMINTRA1.SITB_EMPLEADOR.V_CODESTCON
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvCodestcon(String vCodestcon) {
        this.vCodestcon = vCodestcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.N_ESTMYPE
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.N_ESTMYPE
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public BigDecimal getnEstmype() {
        return nEstmype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.N_ESTMYPE
     *
     * @param nEstmype the value for SIMINTRA1.SITB_EMPLEADOR.N_ESTMYPE
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setnEstmype(BigDecimal nEstmype) {
        this.nEstmype = nEstmype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGACRED
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.V_FLGACRED
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getvFlgacred() {
        return vFlgacred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.V_FLGACRED
     *
     * @param vFlgacred the value for SIMINTRA1.SITB_EMPLEADOR.V_FLGACRED
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setvFlgacred(String vFlgacred) {
        this.vFlgacred = vFlgacred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_DEPORI
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.SUNAT_DEPORI
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getSunatDepori() {
        return sunatDepori;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_DEPORI
     *
     * @param sunatDepori the value for SIMINTRA1.SITB_EMPLEADOR.SUNAT_DEPORI
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setSunatDepori(String sunatDepori) {
        this.sunatDepori = sunatDepori;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_OPERAC
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.SUNAT_OPERAC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getSunatOperac() {
        return sunatOperac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_OPERAC
     *
     * @param sunatOperac the value for SIMINTRA1.SITB_EMPLEADOR.SUNAT_OPERAC
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setSunatOperac(String sunatOperac) {
        this.sunatOperac = sunatOperac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_CORNOV
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.SUNAT_CORNOV
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getSunatCornov() {
        return sunatCornov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_CORNOV
     *
     * @param sunatCornov the value for SIMINTRA1.SITB_EMPLEADOR.SUNAT_CORNOV
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setSunatCornov(String sunatCornov) {
        this.sunatCornov = sunatCornov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_NUMPRO
     *
     * @return the value of SIMINTRA1.SITB_EMPLEADOR.SUNAT_NUMPRO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public String getSunatNumpro() {
        return sunatNumpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIMINTRA1.SITB_EMPLEADOR.SUNAT_NUMPRO
     *
     * @param sunatNumpro the value for SIMINTRA1.SITB_EMPLEADOR.SUNAT_NUMPRO
     *
     * @mbggenerated Tue Jun 28 14:49:41 COT 2016
     */
    public void setSunatNumpro(String sunatNumpro) {
        this.sunatNumpro = sunatNumpro;
    }
}