package pe.gob.sunafil.tramiteext.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.tramiteext.persistence.model.TdmvcRegistro;
import pe.gob.sunafil.tramiteext.persistence.model.TdmvcRegistroExample;
import pe.gob.sunafil.tramiteext.persistence.model.TdmvcRegistroKey;

public interface TdmvcRegistroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int countByExample(TdmvcRegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int deleteByExample(TdmvcRegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int deleteByPrimaryKey(TdmvcRegistroKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int insert(TdmvcRegistro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int insertSelective(TdmvcRegistro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    List<TdmvcRegistro> selectByExample(TdmvcRegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    TdmvcRegistro selectByPrimaryKey(TdmvcRegistroKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int updateByExampleSelective(@Param("record") TdmvcRegistro record, @Param("example") TdmvcRegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int updateByExample(@Param("record") TdmvcRegistro record, @Param("example") TdmvcRegistroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int updateByPrimaryKeySelective(TdmvcRegistro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAMITE.TDMVC_REGISTRO
     *
     * @mbggenerated Wed Jul 06 14:31:38 COT 2016
     */
    int updateByPrimaryKey(TdmvcRegistro record);
}