package pe.gob.sunafil.gestionpersonal.persistence.client;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhmvcMarcacion;
import pe.gob.sunafil.gestionpersonal.persistence.model.RhmvcMarcacionExample;

public interface RhmvcMarcacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int countByExample(RhmvcMarcacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int deleteByExample(RhmvcMarcacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int deleteByPrimaryKey(BigDecimal nCodmarcacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int insert(RhmvcMarcacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int insertSelective(RhmvcMarcacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    List<RhmvcMarcacion> selectByExample(RhmvcMarcacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    RhmvcMarcacion selectByPrimaryKey(BigDecimal nCodmarcacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int updateByExampleSelective(@Param("record") RhmvcMarcacion record, @Param("example") RhmvcMarcacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int updateByExample(@Param("record") RhmvcMarcacion record, @Param("example") RhmvcMarcacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int updateByPrimaryKeySelective(RhmvcMarcacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RRHHSYS.RHMVC_MARCACION
     *
     * @mbggenerated Wed Oct 26 10:50:35 COT 2016
     */
    int updateByPrimaryKey(RhmvcMarcacion record);
}