package pe.gob.sunafil.denunciavirtual.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.denunciavirtual.persistence.model.DlmvdDocxsol;
import pe.gob.sunafil.denunciavirtual.persistence.model.DlmvdDocxsolExample;
import pe.gob.sunafil.denunciavirtual.persistence.model.DlmvdDocxsolKey;

public interface DlmvdDocxsolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int countByExample(DlmvdDocxsolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int deleteByExample(DlmvdDocxsolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int deleteByPrimaryKey(DlmvdDocxsolKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int insert(DlmvdDocxsol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int insertSelective(DlmvdDocxsol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    List<DlmvdDocxsol> selectByExample(DlmvdDocxsolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    DlmvdDocxsol selectByPrimaryKey(DlmvdDocxsolKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByExampleSelective(@Param("record") DlmvdDocxsol record, @Param("example") DlmvdDocxsolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByExample(@Param("record") DlmvdDocxsol record, @Param("example") DlmvdDocxsolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByPrimaryKeySelective(DlmvdDocxsol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLMVD_DOCXSOL
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByPrimaryKey(DlmvdDocxsol record);
}