package pe.gob.sunafil.tramiteext.persistence.model;

public class TdtbcPerxdepKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBC_PERXDEP.V_CODPERSONAL
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    private String vCodpersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBC_PERXDEP.N_NUMDEP
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    private Short nNumdep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBC_PERXDEP.V_CODPERSONAL
     *
     * @return the value of TRAMITE.TDTBC_PERXDEP.V_CODPERSONAL
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public String getvCodpersonal() {
        return vCodpersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBC_PERXDEP.V_CODPERSONAL
     *
     * @param vCodpersonal the value for TRAMITE.TDTBC_PERXDEP.V_CODPERSONAL
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public void setvCodpersonal(String vCodpersonal) {
        this.vCodpersonal = vCodpersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBC_PERXDEP.N_NUMDEP
     *
     * @return the value of TRAMITE.TDTBC_PERXDEP.N_NUMDEP
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public Short getnNumdep() {
        return nNumdep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBC_PERXDEP.N_NUMDEP
     *
     * @param nNumdep the value for TRAMITE.TDTBC_PERXDEP.N_NUMDEP
     *
     * @mbggenerated Fri Apr 15 16:36:02 COT 2016
     */
    public void setnNumdep(Short nNumdep) {
        this.nNumdep = nNumdep;
    }
}