package pe.gob.sunafil.denunciavirtual.persistence.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.sunafil.denunciavirtual.persistence.model.DltbEmpleador;
import pe.gob.sunafil.denunciavirtual.persistence.model.DltbEmpleadorExample;

public interface DltbEmpleadorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int countByExample(DltbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int deleteByExample(DltbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int deleteByPrimaryKey(String vCodemp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int insert(DltbEmpleador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int insertSelective(DltbEmpleador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    List<DltbEmpleador> selectByExample(DltbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    DltbEmpleador selectByPrimaryKey(String vCodemp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByExampleSelective(@Param("record") DltbEmpleador record, @Param("example") DltbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByExample(@Param("record") DltbEmpleador record, @Param("example") DltbEmpleadorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByPrimaryKeySelective(DltbEmpleador record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DENVIRTUAL.DLTB_EMPLEADOR
     *
     * @mbggenerated Fri Apr 22 10:45:50 COT 2016
     */
    int updateByPrimaryKey(DltbEmpleador record);
}