package pe.gob.sunafil.tramiteext.persistence.model;

public class TdtbdTupaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBD_TUPA.N_NUMGRUPO
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    private Short nNumgrupo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBD_TUPA.N_NUMDEP
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    private Short nNumdep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAMITE.TDTBD_TUPA.V_CODTUPA
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    private String vCodtupa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBD_TUPA.N_NUMGRUPO
     *
     * @return the value of TRAMITE.TDTBD_TUPA.N_NUMGRUPO
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    public Short getnNumgrupo() {
        return nNumgrupo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBD_TUPA.N_NUMGRUPO
     *
     * @param nNumgrupo the value for TRAMITE.TDTBD_TUPA.N_NUMGRUPO
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    public void setnNumgrupo(Short nNumgrupo) {
        this.nNumgrupo = nNumgrupo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBD_TUPA.N_NUMDEP
     *
     * @return the value of TRAMITE.TDTBD_TUPA.N_NUMDEP
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    public Short getnNumdep() {
        return nNumdep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBD_TUPA.N_NUMDEP
     *
     * @param nNumdep the value for TRAMITE.TDTBD_TUPA.N_NUMDEP
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    public void setnNumdep(Short nNumdep) {
        this.nNumdep = nNumdep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAMITE.TDTBD_TUPA.V_CODTUPA
     *
     * @return the value of TRAMITE.TDTBD_TUPA.V_CODTUPA
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    public String getvCodtupa() {
        return vCodtupa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAMITE.TDTBD_TUPA.V_CODTUPA
     *
     * @param vCodtupa the value for TRAMITE.TDTBD_TUPA.V_CODTUPA
     *
     * @mbggenerated Thu Jul 21 10:48:37 COT 2016
     */
    public void setvCodtupa(String vCodtupa) {
        this.vCodtupa = vCodtupa;
    }
}